server:
  port: 40000
spring:
  datasource:
      url: jdbc:mysql://${common.jdbc.host}:${common.jdbc.port}/aa?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
      username: ${common.jdbc.username}
      password: ${common.jdbc.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 1
        idle-timeout: 60000
        connection-timeout: 10000

  redis:
      host: ${common.redis.host}
      port: ${common.redis.port}
      database: 5
      jedis:
        pool:
          max-active: 50
          max-wait: 3s
          min-idle: 10
          max-idle: 15

mybatis:
  mapper-locations: classpath:com.tuotiansudai.repository.mapper/*.xml
  type-aliases-package: com.tuotiansudai.repository.model