sign-in:
  image: "leoshi/ttsd-signin-flask"
  volumes:
    - ./signin_service:/app
    - /var/log/signin:/var/log/signin
  ports:
    - "20001:80"
  links:
    - "redis-server"
web:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20002:8080"
  volumes:
    - ./ttsd-web/war:/webapps
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "static-server"
    - "sign-in"
console:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20003:8080"
  volumes:
    - ./ttsd-console/war:/webapps
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "static-server"
    - "sign-in"
activity-console:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20019:8080"
  volumes:
    - ./ttsd-activity-console/war:/webapps
  links:
    - "redis-server"
pay-wrapper:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20004:8080"
  volumes:
    - ./ttsd-pay-wrapper/war:/webapps
    - /workspace/ump_sign/:/workspace/ump_sign
  links:
    - "sms-wrapper"
    - "redis-server"
sms-wrapper:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20005:8080"
  volumes:
    - ./ttsd-sms-wrapper/war:/webapps
  links:
    - "redis-server"
mobile-api:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20006:8080"
  volumes:
    - ./ttsd-mobile-api/war:/webapps
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "sign-in"
activity:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20007:8080"
  volumes:
    - ./ttsd-activity/war:/webapps
  links:
    - "redis-server"
    - "static-server"
point:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20018:8080"
  volumes:
    - ./ttsd-point-web/war:/webapps
  links:
    - "redis-server"
    - "static-server"
redis-server:
  image: "grokzen/redis-cluster"
  ports:
    - "20010:7000"
    - "20011:7001"
    - "20012:7002"
    - "20013:7003"
    - "20014:7004"
    - "20015:7005"
    - "20016:7006"
    - "20017:7007"
worker-all:
  image: "leoshi/ttsd-java7:UTC8"
  volumes:
    - ./ttsd-job-worker/build/distributions:/workspace/tuotian
  command: bash -c "./ttsd-job-worker-all/bin/ttsd-job-worker"
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
worker-invest:
  image: "leoshi/ttsd-java7:UTC8"
  volumes:
    - ./ttsd-job-worker/build/distributions:/workspace/tuotian
  command: bash -c "./ttsd-job-worker-invest/bin/ttsd-job-worker"
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
worker-jpush:
  image: "leoshi/ttsd-java7:UTC8"
  volumes:
    - ./ttsd-job-worker/build/distributions:/workspace/tuotian
  command: bash -c "./ttsd-job-worker-jpush/bin/ttsd-job-worker"
  links:
    - "redis-server"
static-server:
  image: "nginx"
  volumes:
    - ./ttsd-web/build/static:/usr/share/nginx/html:ro
    - ./scripts/docker/ttsd-test-nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "20020:80"
nginx-server_web:
  image: "nginx"
  volumes:
    - ./scripts/docker/ttsd-web-nginx-rewrite.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "20008:6002"
  links:
    - "activity"
    - "web"
    - "ask"
    - "point"
nginx-server_console:
  image: "nginx"
  volumes:
    - ./scripts/docker/ttsd-console-nginx-rewrite.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "30008:6003"
  links:
    - "console"
    - "activity-console"
ask:
  image: "leoshi/ttsd-tomcat8-java7:UTC8"
  ports:
    - "20009:8080"
  volumes:
    - ./ttsd-ask-web/war:/webapps
  links:
    - "redis-server"
    - "static-server"
