sign-in:
  image: "leoshi/ttsd-signin-flask"
  volumes:
    - ./signin_service:/app
    - /var/log/signin:/var/log/signin
  ports:
    - "20001:80"
  links:
    - "redis-server"
web:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20002:8080"
  volumes:
    - ./ttsd-web/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/web:/usr/local/tomcat/logs
    - /var/log/tuotian/web:/var/log/tomcat
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "static-server"
    - "sign-in"
console:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20003:8080"
  volumes:
    - ./ttsd-console/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/console:/usr/local/tomcat/logs
    - /var/log/tuotian/console:/var/log/tomcat
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "static-server"
    - "sign-in"
activity-console:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20019:8080"
  volumes:
    - ./ttsd-activity-console/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/activity-console:/usr/local/tomcat/logs
    - /var/log/tuotian/activity-console:/var/log/tomcat
  links:
    - "redis-server"
    - "sign-in"
pay-wrapper:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20004:8080"
  volumes:
    - /workspace/ump_sign/:/workspace/ump_sign
    - ./ttsd-pay-wrapper/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/pay-wrapper:/usr/local/tomcat/logs
    - /var/log/tuotian/pay-wrapper:/var/log/tomcat
  links:
    - "sms-wrapper"
    - "redis-server"
sms-wrapper:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20005:8080"
  volumes:
    - ./ttsd-sms-wrapper/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/sms-wrapper:/usr/local/tomcat/logs
    - /var/log/tuotian/sms-wrapper:/var/log/tomcat
  links:
    - "redis-server"
mobile-api:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20006:8080"
  volumes:
    - ./ttsd-mobile-api/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/mobile-api:/usr/local/tomcat/logs
    - /var/log/tuotian/mobile-api:/var/log/tomcat
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "sign-in"
activity:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20007:8080"
  volumes:
    - ./ttsd-activity/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/activity:/usr/local/tomcat/logs
    - /var/log/tuotian/activity:/var/log/tomcat
  links:
    - "redis-server"
    - "static-server"
    - "sign-in"
point:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20018:8080"
  volumes:
    - ./ttsd-point-web/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/point-web:/usr/local/tomcat/logs
    - /var/log/tuotian/point-web:/var/log/tomcat
  links:
    - "redis-server"
    - "static-server"
    - "sign-in"
redis-server:
  image: "grokzen/redis-cluster"
  ports:
    - "20010:7000"
    - "20011:7001"
    - "20012:7002"
    - "20013:7003"
    - "20014:7004"
    - "20015:7005"
    - "20016:7006"
    - "20017:7007"
worker-all:
  image: "isuper/java-oracle:jdk_8"
  volumes:
    - ./ttsd-job-worker/build/distributions:/root
    - /var/log/tuotian/worker-all:/var/log/job-worker
  command: bash -c "/root/ttsd-job-worker-all/bin/ttsd-job-worker"
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
worker-invest:
  image: "isuper/java-oracle:jdk_8"
  volumes:
    - ./ttsd-job-worker/build/distributions:/root
    - /var/log/tuotian/worker-invest:/var/log/job-worker
  command: bash -c "/root/ttsd-job-worker-invest/bin/ttsd-job-worker"
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
worker-jpush:
  image: "isuper/java-oracle:jdk_8"
  volumes:
    - ./ttsd-job-worker/build/distributions:/root
    - /var/log/tuotian/worker-jpush:/var/log/job-worker
  command: bash -c "/root/ttsd-job-worker-jpush/bin/ttsd-job-worker"
  links:
    - "redis-server"
static-server:
  image: "nginx"
  volumes:
    - ./ttsd-web/build/static:/usr/share/nginx/html:ro
    - ./scripts/docker/ttsd-test-nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "20020:80"
nginx-server_web:
  image: "nginx"
  volumes:
    - ./scripts/docker/ttsd-web-nginx-rewrite.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "20008:6002"
  links:
    - "activity"
    - "web"
    - "ask"
    - "point"
nginx-server_console:
  image: "nginx"
  volumes:
    - ./scripts/docker/ttsd-console-nginx-rewrite.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "30008:6003"
  links:
    - "console"
    - "activity-console"
ask:
  image: "andreptb/tomcat:8-jdk8"
  ports:
    - "20009:8080"
  volumes:
    - ./ttsd-ask-web/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/ask-web:/usr/local/tomcat/logs
    - /var/log/tuotian/ask-web:/var/log/tomcat
  links:
    - "redis-server"
    - "static-server"
    - "sign-in"
