sign-in:
  image: "leoshi/ttsd-signin-flask"
  volumes:
    - ./signin_service:/app
    - /var/log/tuotian/signin:/var/log/signin
  ports:
    - "20001:80"
  links:
    - "redis-server"
  command: ["/usr/bin/supervisord"]

web:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20002:8080"
  volumes:
    - ./ttsd-web/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/web:/usr/local/tomcat/logs
    - /var/log/tuotian/web:/var/log/tomcat
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "static-server"
    - "sign-in"
    - "anxin-wrapper"

console:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20003:8080"
  volumes:
    - ./ttsd-console/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/console:/usr/local/tomcat/logs
    - /var/log/tuotian/console:/var/log/tomcat
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "static-server"
    - "sign-in"
    - "ask-rest-service"
    - "anxin-wrapper"

pay-wrapper:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20004:8080"
  volumes:
    - /workspace/deploy-config/ttsd-pay-wrapper/:/workspace/deploy-config/ttsd-pay-wrapper
    - ./ttsd-pay-wrapper/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/pay-wrapper:/usr/local/tomcat/logs
    - /var/log/tuotian/pay-wrapper:/var/log/tomcat
  links:
    - "sms-wrapper"
    - "redis-server"

sms-wrapper:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20005:8080"
  volumes:
    - ./ttsd-sms-wrapper/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/sms-wrapper:/usr/local/tomcat/logs
    - /var/log/tuotian/sms-wrapper:/var/log/tomcat
  links:
    - "redis-server"

mobile-api:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
    - "spring.profiles.active=QA"
  ports:
    - "20006:8080"
  volumes:
    - ./ttsd-mobile-api/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/mobile-api:/usr/local/tomcat/logs
    - /var/log/tuotian/mobile-api:/var/log/tomcat
  links:
    - "static-server"
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "sign-in"
    - "anxin-wrapper"

activity:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20007:8080"
  volumes:
    - ./ttsd-activity-web/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/activity:/usr/local/tomcat/logs
    - /var/log/tuotian/activity:/var/log/tomcat
  links:
    - "redis-server"
    - "static-server"
    - "sign-in"

nginx-server_web:
  image: "nginx"
  volumes:
    - ./scripts/docker/ttsd-web-nginx-rewrite.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "20008:6002"
  links:
    - "activity"
    - "web"
    - "ask"
    - "point"

ask:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20009:8080"
  volumes:
    - ./ttsd-ask-web/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/ask-web:/usr/local/tomcat/logs
    - /var/log/tuotian/ask-web:/var/log/tomcat
  links:
    - "redis-server"
    - "static-server"
    - "sign-in"
    - "ask-rest-service"

redis-server:
  image: "grokzen/redis-cluster"
  ports:
    - "20010:7000"
    - "20011:7001"
    - "20012:7002"
    - "20013:7003"
    - "20014:7004"
    - "20015:7005"
    - "20016:7006"
    - "20017:7007"

point:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20018:8080"
  volumes:
    - ./ttsd-point-web/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/point-web:/usr/local/tomcat/logs
    - /var/log/tuotian/point-web:/var/log/tomcat
  links:
    - "redis-server"
    - "static-server"
    - "sign-in"

activity-console:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20019:8080"
  volumes:
    - ./ttsd-activity-console/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/activity-console:/usr/local/tomcat/logs
    - /var/log/tuotian/activity-console:/var/log/tomcat
  links:
    - "redis-server"
    - "sign-in"

static-server:
  image: "nginx"
  volumes:
    - ./ttsd-web/build/static:/usr/share/nginx/html:ro
    - ./scripts/docker/ttsd-test-nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "20020:80"

anxin-wrapper:
  image: "andreptb/tomcat:8-jdk8"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  ports:
    - "20021:8080"
  volumes:
    - /workspace/deploy-config/ttsd-anxin-wrapper/:/workspace/deploy-config/ttsd-anxin-wrapper
    - ./ttsd-anxin-wrapper/war:/usr/local/tomcat/webapps
    - /var/log/tuotian/anxin-wrapper:/usr/local/tomcat/logs
    - /var/log/tuotian/anxin-wrapper:/var/log/tomcat
  links:
    - "sms-wrapper"
    - "redis-server"

nginx-server_console:
  image: "nginx"
  volumes:
    - ./scripts/docker/ttsd-console-nginx-rewrite.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "30008:6003"
  links:
    - "console"
    - "activity-console"

worker-all:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-job-worker/build/distributions:/opt/worker
    - /var/log/tuotian/worker-all:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-job-worker-all/bin/ttsd-job-worker"
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"

worker-jpush:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-job-worker/build/distributions:/opt/worker
    - /var/log/tuotian/worker-jpush:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-job-worker-jpush/bin/ttsd-job-worker"
  links:
    - "redis-server"

worker-repay:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-job-worker/build/distributions:/opt/worker
    - /var/log/tuotian/worker-repay:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-job-worker-repay/bin/ttsd-job-worker"
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"

auditLog-mq-consumer:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-auditLog-mq-consumer/build/distributions:/opt/worker
    - /var/log/tuotian/ttsd-auditLog-mq-consumer:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-auditLog-mq-consumer/bin/ttsd-auditLog-mq-consumer"
  links:
    - "redis-server"

loan-mq-consumer:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-loan-mq-consumer/build/distributions:/opt/worker
    - /var/log/tuotian/ttsd-loan-mq-consumer:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-loan-mq-consumer/bin/ttsd-loan-mq-consumer"
  links:
    - "pay-wrapper"
    - "sms-wrapper"
    - "redis-server"
    - "anxin-wrapper"

message-mq-consumer:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-message-mq-consumer/build/distributions:/opt/worker
    - /var/log/tuotian/ttsd-message-mq-consumer:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-message-mq-consumer/bin/ttsd-message-mq-consumer"
  links:
    - "sms-wrapper"
    - "redis-server"

email-mq-consumer:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-email-mq-consumer/build/distributions:/opt/worker
    - /var/log/tuotian/ttsd-email-mq-consumer:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-email-mq-consumer/bin/ttsd-email-mq-consumer"
  links:
    - "redis-server"

point-mq-consumer:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-point-mq-consumer/build/distributions:/opt/worker
    - /var/log/tuotian/ttsd-point-mq-consumer:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-point-mq-consumer/bin/ttsd-point-mq-consumer"
  links:
    - "sms-wrapper"
    - "redis-server"

activity-mq-consumer:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-activity-mq-consumer/build/distributions:/opt/worker
    - /var/log/tuotian/ttsd-activity-mq-consumer:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-activity-mq-consumer/bin/ttsd-activity-mq-consumer"
  links:
    - "sms-wrapper"
    - "redis-server"

user-mq-consumer:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-user-mq-consumer/build/distributions:/opt/worker
    - /var/log/tuotian/ttsd-user-mq-consumer:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-user-mq-consumer/bin/ttsd-user-mq-consumer"
  links:
    - "sms-wrapper"
    - "redis-server"

ask-rest-service:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-ask-rest/build/distributions:/opt/worker
    - /var/log/tuotian/ttsd-ask-rest:/var/log/tuotian
  command: bash -c "/opt/worker/ttsd-ask-rest/bin/ttsd-ask-rest"
  links:
    - "sms-wrapper"
    - "redis-server"

diagnosis:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx1024m"
  volumes:
    - ./ttsd-diagnosis/build/distributions:/opt/worker
    - /var/log/tuotian/diagnosis:/var/log/job-worker
  command: bash -c "/opt/worker/ttsd-diagnosis/bin/ttsd-diagnosis"
  links:
    - "redis-server"
    - "pay-wrapper"

worker-monitor:
  image: "anapsix/alpine-java:8_jdk"
  environment:
    - "TZ=Asia/Shanghai"
    - "JAVA_OPTS=-Xmx256m"
  volumes:
    - ./ttsd-worker-monitor/build/libs:/opt/worker
    - /var/log/tuotian/worker-monitor:/var/log/job-worker
  command: bash -c "java -Xmx256m -jar /opt/worker/ttsd-worker-monitor.jar"
  links:
    - "redis-server"
    - "sms-wrapper"