package com.tuotiansudai.activity.repository.model;

import com.google.common.collect.Lists;

import java.util.List;

public enum LotteryPrize {
    TOURISM("华东旅游大奖", PrizeType.CONCRETE, ActivityCategory.AUTUMN_PRIZE, 0),
    MANGO_CARD_100("100元芒果卡", PrizeType.CONCRETE, ActivityCategory.AUTUMN_PRIZE, 0.5),
    LUXURY("奢侈品大奖", PrizeType.CONCRETE, ActivityCategory.AUTUMN_PRIZE, 0),
    PORCELAIN_CUP("青花瓷杯子", PrizeType.CONCRETE, ActivityCategory.AUTUMN_PRIZE, 0.5),
    RED_ENVELOPE_100("100元投资红包", PrizeType.VIRTUAL, ActivityCategory.AUTUMN_PRIZE, 20),
    RED_ENVELOPE_50("50元投资红包", PrizeType.VIRTUAL, ActivityCategory.AUTUMN_PRIZE, 25),
    INTEREST_COUPON_5("0.5%加息券", PrizeType.VIRTUAL, ActivityCategory.AUTUMN_PRIZE, 25),
    INTEREST_COUPON_2("0.2%加息券", PrizeType.VIRTUAL, ActivityCategory.AUTUMN_PRIZE, 29.5),

    //1000积分抽奖
    BICYCLE_XM("小米（MI）九号平衡车", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_1000, 0),
    MASK("防雾霾骑行口罩", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_1000, 3),
    LIPSTICK("屈臣氏润唇膏", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_1000, 3),
    PORCELAIN_CUP_BY_1000("青花瓷杯子", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_1000, 1.5),
    PHONE_BRACKET("懒人手机支架", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_1000, 4.5),
    PHONE_CHARGE_10("10元话费", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_1000, 3),
    RED_ENVELOPE_10("10元投资红包", PrizeType.VIRTUAL, ActivityCategory.POINT_DRAW_1000, 45),
    INTEREST_COUPON_2_POINT_DRAW("0.2%加息券", PrizeType.VIRTUAL, ActivityCategory.POINT_DRAW_1000, 40),

    //10000积分抽奖
    IPHONE7_128G("iPhone 7手机128G", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_10000, 0),
    DELAYED_ACTION("通用自拍杆", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_10000, 3),
    U_DISH("拓天速贷U盘", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_10000, 3),
    PHONE_CHARGE_20("20元话费", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_10000, 15),
    HEADREST("车家两用U型头枕", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_10000, 10),
    IQIYI_MEMBERSHIP_30("爱奇艺会员月卡", PrizeType.CONCRETE, ActivityCategory.POINT_DRAW_10000, 15),
    RED_ENVELOPE_50_POINT_DRAW("50元投资红包", PrizeType.VIRTUAL, ActivityCategory.POINT_DRAW_10000, 24),
    INTEREST_COUPON_5_POINT_DRAW("0.5%加息券", PrizeType.VIRTUAL, ActivityCategory.POINT_DRAW_10000, 30),

    //国庆活动
    MEMBERSHIP_V5("一个月V5会员体验", PrizeType.MEMBERSHIP, ActivityCategory.NATIONAL_PRIZE, 25),
    RED_INVEST_15("15元投资红包", PrizeType.VIRTUAL, ActivityCategory.NATIONAL_PRIZE, 30),
    RED_INVEST_50("50元投资红包", PrizeType.VIRTUAL, ActivityCategory.NATIONAL_PRIZE, 30),
    TELEPHONE_FARE_10("10元话费", PrizeType.CONCRETE, ActivityCategory.NATIONAL_PRIZE, 5),
    IQIYI_MEMBERSHIP("一个月爱奇艺会员", PrizeType.CONCRETE, ActivityCategory.NATIONAL_PRIZE, 4),
    CINEMA_TICKET("电影票一张", PrizeType.CONCRETE, ActivityCategory.NATIONAL_PRIZE, 3),
    FLOWER_CUP("青花瓷杯子", PrizeType.CONCRETE, ActivityCategory.NATIONAL_PRIZE, 3),
    IPHONE_7("iphone7", PrizeType.CONCRETE, ActivityCategory.NATIONAL_PRIZE, 0),

    //双11狂欢
    M1_PHONE("锤子M1手机(预定)", PrizeType.CONCRETE, ActivityCategory.CARNIVAL_ACTIVITY, 0),
    HUMIDIFIER("小熊加湿器", PrizeType.CONCRETE, ActivityCategory.CARNIVAL_ACTIVITY, 1),
    HAIR_DRIER("飞科电吹风机", PrizeType.CONCRETE, ActivityCategory.CARNIVAL_ACTIVITY, 1),
    IQIYI_MEMBERSHIP_REF_CARNIVAL("爱奇艺会员", PrizeType.CONCRETE, ActivityCategory.CARNIVAL_ACTIVITY, 5),
    TELEPHONE_FARE_10_REF_CARNIVAL("10元话费", PrizeType.CONCRETE, ActivityCategory.CARNIVAL_ACTIVITY, 5),
    BAMBOO_CHARCOAL_PACKAGE("卡通汽车竹炭包", PrizeType.CONCRETE, ActivityCategory.CARNIVAL_ACTIVITY, 8),
    INTEREST_COUPON_5_POINT_DRAW_REF_CARNIVAL("0.5加息券", PrizeType.VIRTUAL, ActivityCategory.CARNIVAL_ACTIVITY, 41),
    RED_ENVELOPE_50_POINT_DRAW_REF_CARNIVAL("50元红包", PrizeType.VIRTUAL, ActivityCategory.CARNIVAL_ACTIVITY, 39),

    //元旦活动
    MINI_REFRIGERATOR("迷你冰箱", PrizeType.CONCRETE, ActivityCategory.ANNUAL_ACTIVITY, 0),
    ANNUAL_U_DISK("拓天速贷U盘", PrizeType.CONCRETE, ActivityCategory.ANNUAL_ACTIVITY, 1),
    BOLSTER("文字君表情抱枕", PrizeType.CONCRETE, ActivityCategory.ANNUAL_ACTIVITY, 1),
    RED_ENVELOPE_5("5.8元红包", PrizeType.VIRTUAL, ActivityCategory.ANNUAL_ACTIVITY, 3),
    RED_ENVELOPE_3("3.8元红包", PrizeType.VIRTUAL, ActivityCategory.ANNUAL_ACTIVITY, 5),
    RED_ENVELOPE_18("18.8元红包", PrizeType.VIRTUAL, ActivityCategory.ANNUAL_ACTIVITY, 43),
    RED_ENVELOPE_8("8.8元红包", PrizeType.VIRTUAL, ActivityCategory.ANNUAL_ACTIVITY, 45),
    INTEREST_COUPON_2_NEW_YEARS("0.2加息券", PrizeType.VIRTUAL, ActivityCategory.ANNUAL_ACTIVITY, 2),

    //圣诞节活动
    MI_NOTE2_PHONE("小米Note2", PrizeType.CONCRETE, ActivityCategory.CHRISTMAS_ACTIVITY, 0),
    ALOE_CAPSULE("芦荟凝胶", PrizeType.CONCRETE, ActivityCategory.CHRISTMAS_ACTIVITY, 5),
    U_DISK("拓天速贷u盘", PrizeType.CONCRETE, ActivityCategory.CHRISTMAS_ACTIVITY, 5),
    PHONE_FARE_10_REF_CARNIVAL("10元话费", PrizeType.CONCRETE, ActivityCategory.CHRISTMAS_ACTIVITY, 15),
    ELK_PILLOW("麋鹿抱枕", PrizeType.CONCRETE, ActivityCategory.CHRISTMAS_ACTIVITY, 10),
    JOHNSON_HAND_CREAM("强生护手霜", PrizeType.CONCRETE, ActivityCategory.CHRISTMAS_ACTIVITY, 10),
    PUMPKIN_PILLOW("南瓜抱枕", PrizeType.CONCRETE, ActivityCategory.CHRISTMAS_ACTIVITY, 10),
    RED_ENVELOPE_20_POINT_DRAW_REF_CARNIVAL("20元投资红包", PrizeType.VIRTUAL, ActivityCategory.CHRISTMAS_ACTIVITY, 45),

    //今日头条拉新
    T1_PHONE("锤子M1手机(预订)", PrizeType.CONCRETE, ActivityCategory.HEADLINES_TODAY_ACTIVITY, 0),
    BAMBOO_BAG("卡通汽车竹炭包", PrizeType.CONCRETE, ActivityCategory.HEADLINES_TODAY_ACTIVITY, 8),
    FLYCO_HAIR_DRIER("飞科电吹风机", PrizeType.CONCRETE, ActivityCategory.HEADLINES_TODAY_ACTIVITY, 1),
    IQIYI_MEMBERSHIP_MONTH_REF_CARNIVAL("爱奇艺会员月卡", PrizeType.CONCRETE, ActivityCategory.HEADLINES_TODAY_ACTIVITY, 4),
    TELEPHONE_FARE_10_YUAN_REF_CARNIVAL("10元话费", PrizeType.CONCRETE, ActivityCategory.HEADLINES_TODAY_ACTIVITY, 11),
    QQ_EMOTICON_PILLOW("QQ表情靠枕", PrizeType.CONCRETE, ActivityCategory.HEADLINES_TODAY_ACTIVITY, 8),
    INSPISSATE_TOWEL("加厚纯棉毛巾", PrizeType.CONCRETE, ActivityCategory.HEADLINES_TODAY_ACTIVITY, 13),
    RED_ENVELOPE_50_YUAN_DRAW_REF_CARNIVAL("50元红包", PrizeType.VIRTUAL, ActivityCategory.HEADLINES_TODAY_ACTIVITY, 55),

    //元宵节
    LANTERN_FESTIVAL_RED_ENVELOPE_5("5元投资红包", PrizeType.VIRTUAL, ActivityCategory.LANTERN_FESTIVAL_ACTIVITY, 30),
    LANTERN_FESTIVAL_RED_ENVELOPE_8("8元投资红包", PrizeType.VIRTUAL, ActivityCategory.LANTERN_FESTIVAL_ACTIVITY, 15),
    LANTERN_FESTIVAL_RED_ENVELOPE_10("10元投资红包", PrizeType.VIRTUAL, ActivityCategory.LANTERN_FESTIVAL_ACTIVITY, 15),
    LANTERN_FESTIVAL_RED_ENVELOPE_40("40元投资红包", PrizeType.VIRTUAL, ActivityCategory.LANTERN_FESTIVAL_ACTIVITY, 5),
    LANTERN_FESTIVAL_RED_ENVELOPE_30("30元投资红包", PrizeType.VIRTUAL, ActivityCategory.LANTERN_FESTIVAL_ACTIVITY, 10),
    LANTERN_FESTIVAL_INTEREST_COUPON_5("0.5%加息券", PrizeType.VIRTUAL, ActivityCategory.LANTERN_FESTIVAL_ACTIVITY, 20),
    LANTERN_FESTIVAL_PHONE_COST_10("10元话费", PrizeType.CONCRETE, ActivityCategory.LANTERN_FESTIVAL_ACTIVITY, 5),
    LANTERN_FESTIVAL_JD_E_CARD_300("300元京东E卡", PrizeType.CONCRETE, ActivityCategory.LANTERN_FESTIVAL_ACTIVITY, 0),

    //春节活动
    SPRING_FESTIVAL_RED_ENVELOP_68("6.8:投资红包", PrizeType.VIRTUAL, ActivityCategory.SPRING_FESTIVAL_ACTIVITY, 6),
    SPRING_FESTIVAL_RED_ENVELOP_58("5.8:投资红包", PrizeType.VIRTUAL, ActivityCategory.SPRING_FESTIVAL_ACTIVITY, 12),
    SPRING_FESTIVAL_RED_ENVELOP_38("3.8:投资红包", PrizeType.VIRTUAL, ActivityCategory.SPRING_FESTIVAL_ACTIVITY, 16),
    SPRING_FESTIVAL_RED_ENVELOP_18("1.8:投资红包", PrizeType.VIRTUAL, ActivityCategory.SPRING_FESTIVAL_ACTIVITY, 20),
    SPRING_FESTIVAL_RED_ENVELOP_88("8.8:投资红包", PrizeType.VIRTUAL, ActivityCategory.SPRING_FESTIVAL_ACTIVITY, 15),
    SPRING_FESTIVAL_RED_ENVELOP_188("18.8:投资红包", PrizeType.VIRTUAL, ActivityCategory.SPRING_FESTIVAL_ACTIVITY, 15),
    SPRING_FESTIVAL_INTEREST_COUPON_5("0.5:加息券", PrizeType.VIRTUAL, ActivityCategory.SPRING_FESTIVAL_ACTIVITY, 10),
    SPRING_FESTIVAL_INTEREST_COUPON_2("0.2:加息券", PrizeType.VIRTUAL, ActivityCategory.SPRING_FESTIVAL_ACTIVITY, 6),

    //积分商城抽奖
    POINT_SHOP_RED_ENVELOPE_10("10元红包", PrizeType.VIRTUAL, ActivityCategory.POINT_SHOP_DRAW_1000, 12),
    POINT_SHOP_RED_ENVELOPE_50("50元红包", PrizeType.VIRTUAL, ActivityCategory.POINT_SHOP_DRAW_1000, 12),
    POINT_SHOP_INTEREST_COUPON_2("0.2%加息劵", PrizeType.VIRTUAL, ActivityCategory.POINT_SHOP_DRAW_1000, 10),
    POINT_SHOP_INTEREST_COUPON_5("0.5%加息劵", PrizeType.VIRTUAL, ActivityCategory.POINT_SHOP_DRAW_1000, 9),
    POINT_SHOP_POINT_500("500积分", PrizeType.POINT, ActivityCategory.POINT_SHOP_DRAW_1000, 48),
    POINT_SHOP_POINT_3000("3000积分", PrizeType.POINT, ActivityCategory.POINT_SHOP_DRAW_1000, 8),
    POINT_SHOP_PHONE_CHARGE_10("10元话费", PrizeType.CONCRETE, ActivityCategory.POINT_SHOP_DRAW_1000, 1),
    POINT_SHOP_JD_100("100元京东E卡", PrizeType.CONCRETE, ActivityCategory.POINT_SHOP_DRAW_1000, 0),

    //摇钱树活动
    MONEY_TREE_1000_EXPERIENCE_GOLD_0("0元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_1000_ACTIVITY, 60),
    MONEY_TREE_1000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_1000_ACTIVITY, 40),

    MONEY_TREE_10000_EXPERIENCE_GOLD_0("0元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_10000_ACTIVITY, 50),
    MONEY_TREE_10000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_10000_ACTIVITY, 50),

    MONEY_TREE_20000_EXPERIENCE_GOLD_0("0元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_20000_ACTIVITY, 40),
    MONEY_TREE_20000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_20000_ACTIVITY, 40),
    MONEY_TREE_20000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_20000_ACTIVITY, 15),
    MONEY_TREE_20000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_20000_ACTIVITY, 5),

    MONEY_TREE_30000_EXPERIENCE_GOLD_0("0元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_30000_ACTIVITY, 30),
    MONEY_TREE_30000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_30000_ACTIVITY, 35),
    MONEY_TREE_30000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_30000_ACTIVITY, 20),
    MONEY_TREE_30000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_30000_ACTIVITY, 10),
    MONEY_TREE_30000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_30000_ACTIVITY, 5),

    MONEY_TREE_40000_EXPERIENCE_GOLD_0("0元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_40000_ACTIVITY, 20),
    MONEY_TREE_40000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_40000_ACTIVITY, 30),
    MONEY_TREE_40000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_40000_ACTIVITY, 20),
    MONEY_TREE_40000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_40000_ACTIVITY, 20),
    MONEY_TREE_40000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_40000_ACTIVITY, 10),

    MONEY_TREE_50000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_50000_ACTIVITY, 45),
    MONEY_TREE_50000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_50000_ACTIVITY, 20),
    MONEY_TREE_50000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_50000_ACTIVITY, 15),
    MONEY_TREE_50000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_50000_ACTIVITY, 15),
    MONEY_TREE_50000_EXPERIENCE_GOLD_500("500元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_50000_ACTIVITY, 5),

    MONEY_TREE_60000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_60000_ACTIVITY, 35),
    MONEY_TREE_60000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_60000_ACTIVITY, 20),
    MONEY_TREE_60000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_60000_ACTIVITY, 25),
    MONEY_TREE_60000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_60000_ACTIVITY, 10),
    MONEY_TREE_60000_EXPERIENCE_GOLD_500("500元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_60000_ACTIVITY, 5),
    MONEY_TREE_60000_EXPERIENCE_GOLD_600("600元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_60000_ACTIVITY, 5),

    MONEY_TREE_70000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_70000_ACTIVITY, 30),
    MONEY_TREE_70000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_70000_ACTIVITY, 20),
    MONEY_TREE_70000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_70000_ACTIVITY, 20),
    MONEY_TREE_70000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_70000_ACTIVITY, 15),
    MONEY_TREE_70000_EXPERIENCE_GOLD_500("500元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_70000_ACTIVITY, 10),
    MONEY_TREE_70000_EXPERIENCE_GOLD_600("600元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_70000_ACTIVITY, 5),

    MONEY_TREE_80000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_80000_ACTIVITY, 35),
    MONEY_TREE_80000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_80000_ACTIVITY, 20),
    MONEY_TREE_80000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_80000_ACTIVITY, 10),
    MONEY_TREE_80000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_80000_ACTIVITY, 10),
    MONEY_TREE_80000_EXPERIENCE_GOLD_500("500元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_80000_ACTIVITY, 10),
    MONEY_TREE_80000_EXPERIENCE_GOLD_600("600元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_80000_ACTIVITY, 10),
    MONEY_TREE_80000_EXPERIENCE_GOLD_800("800元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_80000_ACTIVITY, 5),

    MONEY_TREE_90000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_90000_ACTIVITY, 30),
    MONEY_TREE_90000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_90000_ACTIVITY, 25),
    MONEY_TREE_90000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_90000_ACTIVITY, 10),
    MONEY_TREE_90000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_90000_ACTIVITY, 10),
    MONEY_TREE_90000_EXPERIENCE_GOLD_500("500元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_90000_ACTIVITY, 10),
    MONEY_TREE_90000_EXPERIENCE_GOLD_600("600元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_90000_ACTIVITY, 5),
    MONEY_TREE_90000_EXPERIENCE_GOLD_800("800元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_90000_ACTIVITY, 5),
    MONEY_TREE_90000_EXPERIENCE_GOLD_1000("1000元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_90000_ACTIVITY, 5),

    MONEY_TREE_100000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_100000_ACTIVITY, 20),
    MONEY_TREE_100000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_100000_ACTIVITY, 15),
    MONEY_TREE_100000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_100000_ACTIVITY, 15),
    MONEY_TREE_100000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_100000_ACTIVITY, 20),
    MONEY_TREE_100000_EXPERIENCE_GOLD_500("500元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_100000_ACTIVITY, 10),
    MONEY_TREE_100000_EXPERIENCE_GOLD_600("600元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_100000_ACTIVITY, 10),
    MONEY_TREE_100000_EXPERIENCE_GOLD_800("800元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_100000_ACTIVITY, 5),
    MONEY_TREE_100000_EXPERIENCE_GOLD_1000("1000元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_UNDER_100000_ACTIVITY, 5),

    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_50("50元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 5),
    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_100("100元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 5),
    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_200("200元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 10),
    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_300("300元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 15),
    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_500("500元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 20),
    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_600("600元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 15),
    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_800("800元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 15),
    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_1000("1000元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 10),
    MONEY_TREE_ABOVE_100000_EXPERIENCE_GOLD_2000("2000元", PrizeType.VIRTUAL, ActivityCategory.MONEY_TREE_ABOVE_100000_ACTIVITY, 5),

    //妇女节抽奖
    WOMAN_DAY_ACTIVITY_ENVELOP_521("5.21元红包", PrizeType.VIRTUAL, ActivityCategory.WOMAN_DAY_ACTIVITY, 10),
    WOMAN_DAY_ACTIVITY_ENVELOP_580("5.80元红包", PrizeType.VIRTUAL, ActivityCategory.WOMAN_DAY_ACTIVITY, 5),
    WOMAN_DAY_ACTIVITY_ENVELOP_880("8.80元红包", PrizeType.VIRTUAL, ActivityCategory.WOMAN_DAY_ACTIVITY, 15),
    WOMAN_DAY_ACTIVITY_ENVELOP_1000("10元红包", PrizeType.VIRTUAL, ActivityCategory.WOMAN_DAY_ACTIVITY, 15),
    WOMAN_DAY_ACTIVITY_INTEREST_COUPON_2("0.2%加息券", PrizeType.VIRTUAL, ActivityCategory.WOMAN_DAY_ACTIVITY, 20),
    WOMAN_DAY_ACTIVITY_ENVELOP_38("38元红包", PrizeType.VIRTUAL, ActivityCategory.WOMAN_DAY_ACTIVITY, 10),
    WOMAN_DAY_ACTIVITY_ENVELOP_38_100("138元红包", PrizeType.VIRTUAL, ActivityCategory.WOMAN_DAY_ACTIVITY, 10),
    WOMAN_DAY_ACTIVITY_INTEREST_COUPON_5("0.5%加息券", PrizeType.VIRTUAL, ActivityCategory.WOMAN_DAY_ACTIVITY, 15),

    // 微信服务号推广抽奖
    WECHAT_LOTTERY_BEDCLOTHES("奢华贡缎床品四件套", PrizeType.CONCRETE, ActivityCategory.WECHAT_FIRST_INVEST_PRIZE, 1),
    WECHAT_LOTTERY_BAG("时尚百搭真皮子母包", PrizeType.CONCRETE, ActivityCategory.WECHAT_FIRST_INVEST_PRIZE, 1),
    WECHAT_LOTTERY_HEADGEAR("简约吊坠百搭锁骨链", PrizeType.CONCRETE, ActivityCategory.WECHAT_FIRST_INVEST_PRIZE, 7),
    WECHAT_LOTTERY_TOWEL("精品定制毛巾礼盒", PrizeType.CONCRETE, ActivityCategory.WECHAT_FIRST_INVEST_PRIZE, 20),
    WECHAT_LOTTERY_RED_ENVELOP_20("20元红包", PrizeType.VIRTUAL, ActivityCategory.WECHAT_FIRST_INVEST_PRIZE, 70),

    //母亲节
    MOTHERS_DAY_ACTIVITY_ENVELOP_5("5元红包", PrizeType.VIRTUAL, ActivityCategory.MOTHERS_DAY_ACTIVITY, 25),
    MOTHERS_DAY_ACTIVITY_ENVELOP_10("10元红包", PrizeType.VIRTUAL, ActivityCategory.MOTHERS_DAY_ACTIVITY, 20),
    MOTHERS_DAY_ACTIVITY_ENVELOP_20("20元红包", PrizeType.VIRTUAL, ActivityCategory.MOTHERS_DAY_ACTIVITY, 19),
    MOTHERS_DAY_ACTIVITY_INTEREST_COUPON_5("0.5%加息券", PrizeType.VIRTUAL, ActivityCategory.MOTHERS_DAY_ACTIVITY, 25),
    MOTHERS_DAY_ACTIVITY_INTEREST_COUPON_1("1%加息券", PrizeType.VIRTUAL, ActivityCategory.MOTHERS_DAY_ACTIVITY, 5),
    MOTHERS_DAY_ACTIVITY_EXPERIENCE_GOLD_888("888元体验金", PrizeType.EXPERIENCE, ActivityCategory.MOTHERS_DAY_ACTIVITY, 5),
    MOTHERS_DAY_ACTIVITY_EXPERIENCE_GOLD_8888("8888元体验金", PrizeType.EXPERIENCE, ActivityCategory.MOTHERS_DAY_ACTIVITY, 1),
    MOTHERS_DAY_ACTIVITY_BEDDING("纯棉四件套", PrizeType.CONCRETE, ActivityCategory.MOTHERS_DAY_ACTIVITY, 0),

    //周年庆单笔
    CELEBRATION_SINGLE_ACTIVITY_ENVELOP_5("5元红包", PrizeType.VIRTUAL,ActivityCategory.CELEBRATION_SINGLE_ACTIVITY,15),
    CELEBRATION_SINGLE_ACTIVITY_ENVELOP_10("10元红包", PrizeType.VIRTUAL,ActivityCategory.CELEBRATION_SINGLE_ACTIVITY,20),
    CELEBRATION_SINGLE_ACTIVITY_ENVELOP_30("30元红包", PrizeType.VIRTUAL,ActivityCategory.CELEBRATION_SINGLE_ACTIVITY,19),
    CELEBRATION_SINGLE_ACTIVITY_COUPON_5("0.5%加息券", PrizeType.VIRTUAL,ActivityCategory.CELEBRATION_SINGLE_ACTIVITY,25),
    CELEBRATION_SINGLE_ACTIVITY_EXPERIENCE_GOLD_888("888元体验金", PrizeType.EXPERIENCE,ActivityCategory.CELEBRATION_SINGLE_ACTIVITY,15),
    CELEBRATION_SINGLE_ACTIVITY_EXPERIENCE_GOLD_2888("2888元体验金", PrizeType.EXPERIENCE,ActivityCategory.CELEBRATION_SINGLE_ACTIVITY,5),
    CELEBRATION_SINGLE_ACTIVITY_LUGGAGE("迷彩旅行箱", PrizeType.CONCRETE,ActivityCategory.CELEBRATION_SINGLE_ACTIVITY,0),
    CELEBRATION_SINGLE_ACTIVITY_DOLL("树袋熊玩偶", PrizeType.CONCRETE,ActivityCategory.CELEBRATION_SINGLE_ACTIVITY,1),

    //运动达人VS职场达人活动
    EXERCISE_WORK_ACTIVITY_ENVELOP_5("5元红包", PrizeType.VIRTUAL,ActivityCategory.EXERCISE_WORK_ACTIVITY,20),
    EXERCISE_WORK_ACTIVITY_ENVELOP_10("10元红包", PrizeType.VIRTUAL,ActivityCategory.EXERCISE_WORK_ACTIVITY,20),
    EXERCISE_WORK_ACTIVITY_ENVELOP_20("20元红包", PrizeType.VIRTUAL,ActivityCategory.EXERCISE_WORK_ACTIVITY,20),
    EXERCISE_WORK_ACTIVITY_ENVELOP_30("30元红包", PrizeType.VIRTUAL,ActivityCategory.EXERCISE_WORK_ACTIVITY,5),
    EXERCISE_WORK_ACTIVITY_COUPON_5("0.5%加息券", PrizeType.VIRTUAL,ActivityCategory.EXERCISE_WORK_ACTIVITY,30),
    EXERCISE_WORK_ACTIVITY_COUPON_8("0.8%加息券", PrizeType.VIRTUAL,ActivityCategory.EXERCISE_WORK_ACTIVITY,5),

    //家装节奖励
    HOUSE_DECORATE_ACTIVITY_ENVELOP_5("5元红包", PrizeType.VIRTUAL,ActivityCategory.HOUSE_DECORATE_ACTIVITY,20),
    HOUSE_DECORATE_ACTIVITY_ENVELOP_8("8元红包", PrizeType.VIRTUAL,ActivityCategory.HOUSE_DECORATE_ACTIVITY,10),
    HOUSE_DECORATE_ACTIVITY_ENVELOP_10("10元红包", PrizeType.VIRTUAL,ActivityCategory.HOUSE_DECORATE_ACTIVITY,15),
    HOUSE_DECORATE_ACTIVITY_ENVELOP_15("15元红包", PrizeType.VIRTUAL,ActivityCategory.HOUSE_DECORATE_ACTIVITY,10),
    HOUSE_DECORATE_ACTIVITY_COUPON_5("0.5%加息券", PrizeType.VIRTUAL,ActivityCategory.HOUSE_DECORATE_ACTIVITY,35),
    HOUSE_DECORATE_ACTIVITY_COUPON_8("0.8%加息券", PrizeType.VIRTUAL,ActivityCategory.HOUSE_DECORATE_ACTIVITY,10),

    //开学季奖励
    SCHOOL_SEASON_ACTIVITY_ENVELOP_2_99("2.99元红包", PrizeType.VIRTUAL,ActivityCategory.SCHOOL_SEASON_ACTIVITY,5),
    SCHOOL_SEASON_ACTIVITY_ENVELOP_5_99("5.99元红包", PrizeType.VIRTUAL,ActivityCategory.SCHOOL_SEASON_ACTIVITY,10),
    SCHOOL_SEASON_ACTIVITY_ENVELOP_6_99("6.99元红包", PrizeType.VIRTUAL,ActivityCategory.SCHOOL_SEASON_ACTIVITY,10),
    SCHOOL_SEASON_ACTIVITY_ENVELOP_9_99("9.99元红包", PrizeType.VIRTUAL,ActivityCategory.SCHOOL_SEASON_ACTIVITY,10),
    SCHOOL_SEASON_ACTIVITY_ENVELOP_19_99("19.99元红包", PrizeType.VIRTUAL,ActivityCategory.SCHOOL_SEASON_ACTIVITY,10),
    SCHOOL_SEASON_ACTIVITY_COUPON_5("0.5%加息券", PrizeType.VIRTUAL,ActivityCategory.SCHOOL_SEASON_ACTIVITY,40),
    SCHOOL_SEASON_ACTIVITY_EXPERIENCE_GOLD_99("99元体验金", PrizeType.EXPERIENCE,ActivityCategory.SCHOOL_SEASON_ACTIVITY,10),
    SCHOOL_SEASON_ACTIVITY_EXPERIENCE_GOLD_999("999元体验金", PrizeType.EXPERIENCE,ActivityCategory.SCHOOL_SEASON_ACTIVITY,5),

    //iphoneX活动
    IPHONEX_ACTIVITY_ENVELOP_ENVELOP_18("18元红包", PrizeType.VIRTUAL,ActivityCategory.IPHONEX_ACTIVITY,15),
    IPHONEX_ACTIVITY_ENVELOP_ENVELOP_188("188元红包", PrizeType.VIRTUAL,ActivityCategory.IPHONEX_ACTIVITY,25),
    IPHONEX_ACTIVITY_ENVELOP_ENVELOP_288("288元红包", PrizeType.VIRTUAL,ActivityCategory.IPHONEX_ACTIVITY,20),
    IPHONEX_ACTIVITY_ENVELOP_ENVELOP_588("588元红包", PrizeType.VIRTUAL,ActivityCategory.IPHONEX_ACTIVITY,15),
    IPHONEX_ACTIVITY_ENVELOP_COUPON_5("0.5%加息券", PrizeType.VIRTUAL,ActivityCategory.IPHONEX_ACTIVITY,10),
    IPHONEX_ACTIVITY_ENVELOP_EXPERIENCE_GOLD_88("88元体验金", PrizeType.EXPERIENCE,ActivityCategory.IPHONEX_ACTIVITY,10),
    IPHONEX_ACTIVITY_ENVELOP_EXPERIENCE_GOLD_888("888元体验金", PrizeType.EXPERIENCE,ActivityCategory.IPHONEX_ACTIVITY,5),
    IPHONEX_ACTIVITY_ENVELOP_EXPERIENCE_IPHONEX("iPhoneX", PrizeType.CONCRETE,ActivityCategory.IPHONEX_ACTIVITY,0),

    //双11剁手活动
    DOUBLE_ELEVEN_ACTIVITY_JD_E_CARD_200("200元京东E卡", PrizeType.CONCRETE, ActivityCategory.DOUBLE_ELEVEN_ACTIVITY, 0),
    DOUBLE_ELEVEN_ACTIVITY_EXPERIENCE_GOLD_1000("1000元体验金", PrizeType.EXPERIENCE,ActivityCategory.DOUBLE_ELEVEN_ACTIVITY,5),
    DOUBLE_ELEVEN_ACTIVITY_ENVELOP_20("20元红包", PrizeType.VIRTUAL,ActivityCategory.DOUBLE_ELEVEN_ACTIVITY,10),
    DOUBLE_ELEVEN_ACTIVITY_ENVELOP_50("50元红包", PrizeType.VIRTUAL,ActivityCategory.DOUBLE_ELEVEN_ACTIVITY,5),
    DOUBLE_ELEVEN_ACTIVITY_ENVELOP_100("100元红包", PrizeType.VIRTUAL,ActivityCategory.DOUBLE_ELEVEN_ACTIVITY,10),
    DOUBLE_ELEVEN_ACTIVITY_ENVELOP_200("200元红包", PrizeType.VIRTUAL,ActivityCategory.DOUBLE_ELEVEN_ACTIVITY,5),
    DOUBLE_ELEVEN_ACTIVITY_INTEREST_COUPON_2("0.2%加息券", PrizeType.VIRTUAL, ActivityCategory.DOUBLE_ELEVEN_ACTIVITY, 5),
    DOUBLE_ELEVEN_ACTIVITY_INTEREST_COUPON_5("0.5%加息券", PrizeType.VIRTUAL, ActivityCategory.DOUBLE_ELEVEN_ACTIVITY, 60),

    //年终奖活动
    YEAR_END_AWARDS_ACTIVITY_JD_E_CARD_200("200元京东E卡", PrizeType.CONCRETE, ActivityCategory.YEAR_END_AWARDS_ACTIVITY, 0),
    YEAR_END_AWARDS_ACTIVITY_EXPERIENCE_GOLD_500("500元体验金", PrizeType.EXPERIENCE, ActivityCategory.YEAR_END_AWARDS_ACTIVITY, 5),
    YEAR_END_AWARDS_ACTIVITY_ENVELOP_10("10元红包", PrizeType.VIRTUAL, ActivityCategory.YEAR_END_AWARDS_ACTIVITY, 15),
    YEAR_END_AWARDS_ACTIVITY_ENVELOP_20("20元红包", PrizeType.VIRTUAL, ActivityCategory.YEAR_END_AWARDS_ACTIVITY, 15),
    YEAR_END_AWARDS_ACTIVITY_ENVELOP_50("50元红包", PrizeType.VIRTUAL, ActivityCategory.YEAR_END_AWARDS_ACTIVITY, 20),
    YEAR_END_AWARDS_ACTIVITY_ENVELOP_100("100元红包", PrizeType.VIRTUAL, ActivityCategory.YEAR_END_AWARDS_ACTIVITY, 15),
    YEAR_END_AWARDS_ACTIVITY_ENVELOP_120("120元红包", PrizeType.VIRTUAL, ActivityCategory.YEAR_END_AWARDS_ACTIVITY, 15),
    YEAR_END_AWARDS_ACTIVITY_ENVELOP_200("200元红包", PrizeType.VIRTUAL, ActivityCategory.YEAR_END_AWARDS_ACTIVITY, 15);

    String description;
    PrizeType prizeType;
    ActivityCategory activityCategory;
    double rate;

    LotteryPrize(String description, PrizeType prizeType, ActivityCategory activityCategory, double rate) {
        this.description = description;
        this.activityCategory = activityCategory;
        this.prizeType = prizeType;
        this.rate = rate;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public PrizeType getPrizeType() {
        return prizeType;
    }

    public void setPrizeType(PrizeType prizeType) {
        this.prizeType = prizeType;
    }

    public ActivityCategory getActivityCategory() {
        return activityCategory;
    }

    public void setActivityCategory(ActivityCategory activityCategory) {
        this.activityCategory = activityCategory;
    }

    public double getRate() {
        return rate;
    }

    public void setRate(double rate) {
        this.rate = rate;
    }

    public static List<LotteryPrizeView> getActivityPrize(ActivityCategory activityCategory) {
        List list = Lists.newArrayList();
        LotteryPrize[] lotteryPrizes = LotteryPrize.values();
        for (LotteryPrize lotteryPrize : lotteryPrizes) {
            if (activityCategory.equals(lotteryPrize.getActivityCategory())) {
                list.add(new LotteryPrizeView(lotteryPrize.name(), lotteryPrize.getDescription()));
            }
        }
        return list;
    }
}
