package com.tuotiansudai.cfca.test;

import java.util.HashMap;
import java.util.Map;

import cfca.sadk.algorithm.common.PKIException;
import cfca.trustsign.common.vo.cs.CreateContractVO;
import cfca.trustsign.common.vo.cs.HeadVO;
import cfca.trustsign.common.vo.cs.SignInfoVO;
import cfca.trustsign.common.vo.request.tx3.Tx3201ReqVO;
import com.tuotiansudai.cfca.connector.HttpConnector;
import com.tuotiansudai.cfca.constant.Request;
import com.tuotiansudai.cfca.converter.JsonObjectMapper;
import com.tuotiansudai.cfca.util.SecurityUtil;

public class Test3201 {
    public static void main(String[] args) throws PKIException {
        HttpConnector httpConnector = new HttpConnector();
        httpConnector.init();

        Tx3201ReqVO tx3201ReqVO = new Tx3201ReqVO();
        HeadVO head = new HeadVO();
        head.setTxTime("20160102235959");

        Map<String, String> fieldMap = new HashMap<String, String>();
        CreateContractVO createContract = new CreateContractVO();

        createContract.setIsSign(0);
        createContract.setTemplateId("7");
        fieldMap.put("text1", "2016");
        fieldMap.put("text2", "3");
        fieldMap.put("text3", "16");
        fieldMap.put("text4", "孙一");
        fieldMap.put("text5", "222321199112050001");
        fieldMap.put("text6", "1");
        fieldMap.put("text7", "1");
        fieldMap.put("text8", "1");
        fieldMap.put("text9", "10000");
        fieldMap.put("text10", "1");
        fieldMap.put("text11", "10000");
        fieldMap.put("text12", "1");
        fieldMap.put("text13", "10000");
        fieldMap.put("text14", "1");
        fieldMap.put("text15", "30000");
        fieldMap.put("text16", "10000");
        fieldMap.put("text17", "10000");
        fieldMap.put("text18", "10000");
        fieldMap.put("text19", "1");
        fieldMap.put("text20", "1");
        // fieldMap.put("text21", "001");
        // fieldMap.put("text22", "1111");
        // fieldMap.put("text23", "1111");
        // fieldMap.put("text24", "1111");
        // fieldMap.put("text25", "1111");
        // fieldMap.put("text26", "1111");
        // fieldMap.put("text27", "1111");
        // fieldMap.put("text28", "1111");
        // fieldMap.put("text29", "1111");
        // fieldMap.put("text30", "1111");
        // fieldMap.put("text31", "1111");
        // fieldMap.put("text32", "1111");
        // fieldMap.put("text33", "1111");
        // fieldMap.put("text34", "1111");
        // fieldMap.put("text35", "1111");
        // fieldMap.put("text36", "1111");
        // fieldMap.put("text37", "1111");
        // fieldMap.put("text38", "1111");
        // fieldMap.put("text39", "1111");
        // fieldMap.put("text40", "1111");
        // fieldMap.put("text41", "1111");
        // fieldMap.put("text42", "1111");
        // fieldMap.put("text43", "1111");
        // fieldMap.put("text44", "1111");
        // fieldMap.put("text45", "1111");
        // fieldMap.put("text46", "1111");
        // fieldMap.put("text47", "1111");
        // fieldMap.put("text48", "1111");
        // fieldMap.put("text49", "1111");
        // fieldMap.put("text50", "1111");
        // fieldMap.put("text51", "1111");
        // fieldMap.put("text52", "1111");
        // fieldMap.put("text53", "1111");
        // fieldMap.put("text54", "1111");
        // fieldMap.put("text55", "1111");
        // fieldMap.put("text56", "1111");
        // fieldMap.put("text57", "1111");
        // fieldMap.put("text58", "1111");
        // fieldMap.put("text59", "1111");
        // fieldMap.put("text60", "1111");
        // fieldMap.put("text61", "1111");
        // fieldMap.put("text62", "1111");
        // fieldMap.put("text63", "1111");
        // fieldMap.put("text64", "1111");
        // fieldMap.put("text65", "1111");
        // fieldMap.put("text66", "1111");
        // fieldMap.put("text67", "1111");
        // fieldMap.put("text68", "1111");
        // fieldMap.put("text69", "1111");
        // fieldMap.put("text70", "1111");
        // fieldMap.put("text71", "1111");
        // fieldMap.put("text72", "1111");
        // fieldMap.put("text73", "1111");
        // fieldMap.put("text74", "1111");
        // fieldMap.put("text75", "1111");
        // fieldMap.put("text76", "1111");
        // fieldMap.put("text77", "1111");
        // fieldMap.put("text78", "1111");
        // fieldMap.put("text79", "1111");
        // fieldMap.put("text80", "1111");
        // fieldMap.put("text81", "1111");
        // fieldMap.put("text82", "1111");
        // fieldMap.put("text83", "1111");
        // fieldMap.put("text84", "1111");
        // fieldMap.put("text85", "1111");
        // fieldMap.put("text86", "1111");
        // fieldMap.put("text87", "1111");
        // fieldMap.put("text88", "1111");
        // fieldMap.put("text89", "1111");
        // fieldMap.put("text90", "1111");
        // fieldMap.put("text91", "1111");
        // fieldMap.put("text92", "1111");
        // fieldMap.put("text93", "1111");
        // fieldMap.put("text94", "1111");
        // fieldMap.put("text95", "1111");
        // fieldMap.put("text96", "1111");
        // fieldMap.put("text97", "1111");
        // fieldMap.put("text98", "1111");
        // fieldMap.put("text99", "1111");
        // fieldMap.put("text100", "111");
        // fieldMap.put("text101", "111");
        // fieldMap.put("text102", "111");
        // fieldMap.put("text103", "111");
        // fieldMap.put("text104", "111");
        // fieldMap.put("text105", "111");
        // fieldMap.put("text106", "111");
        // fieldMap.put("text107", "111");
        // fieldMap.put("text108", "111");
        // fieldMap.put("text109", "111");
        // fieldMap.put("text110", "111");
        // fieldMap.put("text111", "111");
        // fieldMap.put("text112", "111");
        // fieldMap.put("text113", "111");
        // fieldMap.put("text114", "111");
        // fieldMap.put("text115", "111");
        // fieldMap.put("text116", "111");
        // fieldMap.put("text117", "111");
        // fieldMap.put("text118", "111");
        // fieldMap.put("text119", "111");
        // fieldMap.put("text120", "111");
        // fieldMap.put("text121", "111");
        // fieldMap.put("text122", "111");
        // fieldMap.put("text123", "111");
        // fieldMap.put("text124", "111");
        // fieldMap.put("text125", "111");
        // fieldMap.put("text126", "111");
        // fieldMap.put("text127", "111");
        // fieldMap.put("text128", "111");
        // fieldMap.put("text129", "111");
        // fieldMap.put("text130", "111");
        // fieldMap.put("text131", "111");
        // fieldMap.put("text132", "111");
        // fieldMap.put("text133", "111");
        // fieldMap.put("text134", "111");
        // fieldMap.put("text135", "111");
        // fieldMap.put("text136", "111");
        // fieldMap.put("text137", "111");
        // fieldMap.put("text138", "111");

        // createContract.setTemplateId("2");
        // fieldMap.put("text1", "2016");
        // fieldMap.put("text2", "3");
        // fieldMap.put("text3", "16");
        // fieldMap.put("text4", "孙一");
        // fieldMap.put("text5", "222321199112050001");
        // fieldMap.put("text6", "成都");
        // fieldMap.put("text7", "壹萬");
        // fieldMap.put("text8", "叁萬元整");
        // fieldMap.put("text9", "30000");
        // fieldMap.put("text10", "壹萬元整");
        // fieldMap.put("text11", "10000");
        // fieldMap.put("text12", "壹萬元整");
        // fieldMap.put("text13", "10000");
        // fieldMap.put("text14", "壹萬元整");
        // fieldMap.put("text15", "10000");
        // fieldMap.put("text16", "孙一");
        // fieldMap.put("text17", "成都支行");
        // fieldMap.put("text18", "001");

        // createContract.setTemplateId("3");
        // fieldMap.put("text1", "2016");
        // fieldMap.put("text2", "3");
        // fieldMap.put("text3", "16");
        // fieldMap.put("text4", "孙一");
        // fieldMap.put("text5", "222321199112050001");
        // fieldMap.put("text6", "成都");
        // fieldMap.put("text7", "买车");
        // fieldMap.put("text8", "叁萬元整");
        // fieldMap.put("text9", "叁萬元整");
        // fieldMap.put("text10", "零元整");
        // fieldMap.put("text11", "一");
        // fieldMap.put("text12", "10");
        // fieldMap.put("text13", "2016年4月16号");
        // fieldMap.put("text14", "孙一");
        // fieldMap.put("text15", "001");
        // fieldMap.put("text16", "成都支行");

        // createContract.setTemplateId("4");
        // fieldMap.put("text1", "2016");
        // fieldMap.put("text2", "3");
        // fieldMap.put("text3", "16");
        // fieldMap.put("text4", "孙一");
        // fieldMap.put("text5", "222321199112050001");
        // fieldMap.put("text6", "成都");
        // fieldMap.put("text7", "叁萬元整");
        // fieldMap.put("text8", "买车");
        // fieldMap.put("text9", "孙一");
        // fieldMap.put("text10", "001");
        // fieldMap.put("text11", "成都支行");
        // fieldMap.put("text12", "买车");
        // fieldMap.put("text13", "叁萬元整");
        // fieldMap.put("text14", "叁萬元整");
        // fieldMap.put("text15", "叁萬元整");
        // fieldMap.put("text16", "一");
        // fieldMap.put("text17", "10");
        // fieldMap.put("text18", "2016年4月16号");
        // fieldMap.put("text19", "孙一");
        // fieldMap.put("text20", "001");
        // fieldMap.put("text21", "成都支行");

        // createContract.setTemplateId("5");
        // fieldMap.put("text1", "2016");
        // fieldMap.put("text2", "3");
        // fieldMap.put("text3", "16");
        // fieldMap.put("text4", "孙一");
        // fieldMap.put("text5", "222321199112050001");
        // fieldMap.put("text6", "成都");
        // fieldMap.put("text7", "叁萬元整");
        // fieldMap.put("text8", "买车");
        // fieldMap.put("text9", "孙一");
        // fieldMap.put("text10", "001");
        // fieldMap.put("text11", "成都支行");
        // fieldMap.put("text12", "买车");
        // fieldMap.put("text13", "叁萬元整");
        // fieldMap.put("text14", "叁萬元整");
        // fieldMap.put("text15", "一");
        // fieldMap.put("text16", "叁萬元整");
        // fieldMap.put("text17", "一");
        // fieldMap.put("text18", "10");
        // fieldMap.put("text19", "2016年4月16号");
        // fieldMap.put("text20", "孙一");
        // fieldMap.put("text21", "001");
        // fieldMap.put("text22", "成都支行");

        // createContract.setTemplateId("6");
        // fieldMap.put("text1", "孙");
        // fieldMap.put("text2", "13800138001");
        // fieldMap.put("text3", "叁萬");
        // fieldMap.put("text4", "10");
        // fieldMap.put("text5", "58903552");
        // fieldMap.put("text6", "壹");
        // fieldMap.put("text7", "叁");
        // fieldMap.put("text8", "58903552");
        // fieldMap.put("text9", "58903552");
        // fieldMap.put("text10", "壹贰叁");
        // fieldMap.put("text11", "壹贰叁");
        // fieldMap.put("text12", "壹贰叁");
        // fieldMap.put("text13", "壹贰叁");
        // fieldMap.put("text14", "壹贰叁");
        // fieldMap.put("text15", "壹贰叁");
        // fieldMap.put("text16", "壹贰叁");
        // fieldMap.put("text17", "壹贰叁");
        // fieldMap.put("text18", "壹贰叁");
        // fieldMap.put("text19", "壹贰叁");
        // fieldMap.put("text20", "壹贰叁");
        // fieldMap.put("text21", "壹贰叁");
        // fieldMap.put("text22", "壹贰叁");
        // fieldMap.put("text23", "壹贰叁");
        // fieldMap.put("text24", "壹贰叁");
        // fieldMap.put("text25", "壹贰叁");
        // fieldMap.put("text26", "壹贰叁");
        // fieldMap.put("text27", "壹贰叁");
        // fieldMap.put("text28", "壹贰叁");
        // fieldMap.put("text29", "壹贰叁");
        // fieldMap.put("text30", "壹贰叁");
        // fieldMap.put("text31", "壹贰叁");
        // fieldMap.put("text32", "壹贰叁");
        // fieldMap.put("text33", "壹贰叁");
        // fieldMap.put("text34", "壹贰叁");
        // fieldMap.put("text35", "壹贰叁");
        // fieldMap.put("text36", "壹贰叁");
        // fieldMap.put("text37", "壹贰叁");
        // fieldMap.put("text38", "壹贰叁");
        // fieldMap.put("text39", "壹贰叁");
        // fieldMap.put("text40", "壹贰叁");
        // fieldMap.put("text41", "壹贰叁");
        // fieldMap.put("text42", "壹贰叁");
        // fieldMap.put("text43", "壹贰叁");
        // fieldMap.put("text44", "壹贰叁");
        // fieldMap.put("text45", "壹贰叁");
        // fieldMap.put("text46", "壹贰叁");
        // fieldMap.put("text47", "壹贰叁");
        // fieldMap.put("text48", "壹贰叁");
        // fieldMap.put("text49", "壹贰叁");
        // fieldMap.put("text50", "壹贰叁");
        // fieldMap.put("text51", "壹贰叁");
        // fieldMap.put("text52", "壹贰叁");
        // fieldMap.put("text53", "壹贰叁");
        // fieldMap.put("text54", "壹贰叁");
        // fieldMap.put("text55", "壹贰叁");
        // fieldMap.put("text56", "壹贰叁");
        // fieldMap.put("text57", "壹贰叁");
        // fieldMap.put("text58", "壹贰叁");
        // fieldMap.put("text59", "壹贰叁");
        // fieldMap.put("text60", "壹贰叁");
        // fieldMap.put("text61", "壹贰叁");
        // fieldMap.put("text62", "壹贰叁");
        // fieldMap.put("text63", "壹贰叁");
        // fieldMap.put("text64", "壹贰叁");
        // fieldMap.put("text65", "壹贰叁");
        // fieldMap.put("text66", "壹贰叁");
        // fieldMap.put("text67", "壹贰叁");
        // fieldMap.put("text68", "壹贰叁");
        // fieldMap.put("text69", "壹贰叁");
        // fieldMap.put("text70", "壹贰叁");
        // fieldMap.put("text71", "壹贰叁");
        // fieldMap.put("text72", "壹贰叁");
        // fieldMap.put("text73", "壹贰叁");
        // fieldMap.put("text74", "壹贰叁");
        // fieldMap.put("text75", "壹贰叁");
        // fieldMap.put("text76", "壹贰叁");
        // fieldMap.put("text77", "壹贰叁");
        // fieldMap.put("text78", "壹贰叁");
        // fieldMap.put("text79", "壹贰叁");
        // fieldMap.put("text80", "壹贰叁");
        // fieldMap.put("text81", "壹贰叁");
        // fieldMap.put("text82", "壹贰叁");
        // fieldMap.put("text83", "壹贰叁");
        // fieldMap.put("text84", "壹贰叁");
        // fieldMap.put("text85", "壹贰叁");
        // fieldMap.put("text86", "壹贰叁");
        // fieldMap.put("text87", "壹贰叁");
        // fieldMap.put("text88", "壹贰叁");
        // fieldMap.put("text89", "壹贰叁");
        // fieldMap.put("text90", "壹贰叁");
        // fieldMap.put("text91", "壹贰叁");
        // fieldMap.put("text92", "壹贰叁");
        // fieldMap.put("text93", "壹贰叁");
        // fieldMap.put("text94", "壹贰叁");
        // fieldMap.put("text95", "壹贰叁");
        // fieldMap.put("text96", "壹贰叁");
        // fieldMap.put("text97", "壹贰叁");
        // fieldMap.put("text98", "壹贰叁");
        // fieldMap.put("text99", "壹贰叁");
        // fieldMap.put("text100", "壹贰叁");
        // fieldMap.put("text101", "壹贰叁");
        // fieldMap.put("text102", "壹贰叁");
        // fieldMap.put("text103", "壹贰叁");
        // fieldMap.put("text104", "壹贰叁");
        // fieldMap.put("text105", "壹贰叁");
        // fieldMap.put("text106", "壹贰叁");
        // fieldMap.put("text107", "壹贰叁");
        // fieldMap.put("text108", "壹贰叁");
        // fieldMap.put("text109", "壹贰叁");
        // fieldMap.put("text110", "壹贰叁");
        // fieldMap.put("text111", "壹贰叁");
        // fieldMap.put("text112", "壹贰叁");
        // fieldMap.put("text113", "壹贰叁");
        // fieldMap.put("text114", "壹贰叁");
        // fieldMap.put("text115", "壹贰叁");
        // fieldMap.put("text116", "壹贰叁");
        // fieldMap.put("text117", "壹贰叁");
        // fieldMap.put("text118", "壹贰叁");
        // fieldMap.put("text119", "壹贰叁");
        // fieldMap.put("text120", "壹贰叁");
        // fieldMap.put("text121", "壹贰叁");
        // fieldMap.put("text122", "壹贰叁");
        // fieldMap.put("text123", "壹贰叁");
        // fieldMap.put("text124", "壹贰叁");
        // fieldMap.put("text125", "壹贰叁");
        // fieldMap.put("text126", "壹贰叁");
        // fieldMap.put("text127", "壹贰叁");
        // fieldMap.put("text128", "壹贰叁");
        // fieldMap.put("text129", "壹贰叁");
        // fieldMap.put("text130", "壹贰叁");
        // fieldMap.put("text131", "壹贰叁");
        // fieldMap.put("text132", "壹贰叁");
        // fieldMap.put("text133", "壹贰叁");
        // fieldMap.put("text134", "壹贰叁");
        // fieldMap.put("text135", "壹贰叁");
        // fieldMap.put("text136", "壹贰叁");
        // fieldMap.put("text137", "壹贰叁");
        // fieldMap.put("text138", "2016年4月16号");

        createContract.setInvestmentInfo(fieldMap);

        SignInfoVO[] signInfos = new SignInfoVO[1];
        SignInfoVO signInfoVO0 = new SignInfoVO();
        signInfoVO0.setUserId("35FE921E7CF0F890E050007F01004E8E");
        signInfoVO0.setIsProxySign(1);
        signInfoVO0.setLocation("成都");
        signInfoVO0.setProjectCode("003");
        signInfoVO0.setSignLocation("Signature1");
        signInfoVO0.setAuthorizationTime("20160214171200");
        signInfos[0] = signInfoVO0;

        // SignInfoVO signInfoVO1 = new SignInfoVO();
        // signInfoVO1.setUserId("D664AA805F2349F3BB34A35B7B3B4A07");
        // signInfoVO1.setIsProxySign(1);
        // signInfoVO1.setLocation("成都1");
        // signInfoVO1.setProjectCode("003");
        // signInfoVO1.setSignLocation("Signature1;Signature2;Signature3");
        // signInfoVO1.setAuthorizationTime("20160214171200");
        // signInfos[1] = signInfoVO1;

        createContract.setSignInfos(signInfos);

        tx3201ReqVO.setHead(head);
        tx3201ReqVO.setCreateContract(createContract);

        JsonObjectMapper jsonObjectMapper = new JsonObjectMapper();
        String req = jsonObjectMapper.writeValueAsString(tx3201ReqVO);
        System.out.println("req:" + req);

        String txCode = "3201";
        String signature = SecurityUtil.p7SignMessageDetach(HttpConnector.JKS_PATH, HttpConnector.JKS_PWD, HttpConnector.ALIAS, req);
        String res = httpConnector.post("platId/" + Request.PLAT_ID + "/txCode/" + txCode + "/transaction", req, signature);
        System.out.println("res:" + res);
    }
}
