LOAN_STATUS_APPROVING = 'APPROVING'
LOAN_STATUS_APPROVED = 'APPROVED'
LOAN_STATUS_EXPIRED = 'EXPIRED'

LOAN_STATUS_CHOICES = (
    (LOAN_STATUS_APPROVING, u'待审核')
    (LOAN_STATUS_APPROVED, u'已审核')
    (LOAN_STATUS_EXPIRED, u'已过期')
)

LOAN_TYPE_HOUSE = 'HOUSE'
LOAN_TYPE_VEHICLE = 'VEHICLE'
LOAN_TYPE_FACTORING = 'FACTORING'
LOAN_TYPE_BILL = 'BILL'
LOAN_TYPE_HUIZU = 'HUIZU'

LOAN_TYPE_CHOICES = (
    (LOAN_TYPE_HOUSE, u'房')
    (LOAN_TYPE_VEHICLE, u'车')
    (LOAN_TYPE_FACTORING, u'保理')
    (LOAN_TYPE_BILL, u'票据')
    (LOAN_TYPE_HUIZU, u'慧租')
)
