# coding=utf-8
LOAN_STATUS_APPROVING = 'APPROVING'
LOAN_STATUS_APPROVED = 'APPROVED'
LOAN_STATUS_EXPIRED = 'EXPIRED'
LOAN_STATUS_REJECT = 'REJECT'

LOAN_STATUS_CHOICES = (
    (LOAN_STATUS_APPROVING, u'待审核'),
    (LOAN_STATUS_APPROVED, u'已审核'),
    (LOAN_STATUS_EXPIRED, u'已过期'),
    (LOAN_STATUS_REJECT, u'已驳回'),

)

LOAN_TYPE_HOUSE = 'HOUSE'
LOAN_TYPE_VEHICLE = 'VEHICLE'
LOAN_TYPE_FACTORING = 'FACTORING'
LOAN_TYPE_BILL = 'BILL'
LOAN_TYPE_HUIZU = 'HUIZU'
LOAN_TYPE_SHUIYI = 'SHUIYI'

LOAN_TYPE_CHOICES = (
    (LOAN_TYPE_HOUSE, u'房产抵押借款'),
    (LOAN_TYPE_VEHICLE, u'车辆抵押借款'),
    (LOAN_TYPE_FACTORING, u'企业经营性借款-保理'),
    (LOAN_TYPE_BILL, u'企业经营性借款-票据'),
    (LOAN_TYPE_SHUIYI, u'税易经营性借款'),
    (LOAN_TYPE_HUIZU, u'汽车融资租赁')
)


class OperationTarget(object):
    LOAN = 'loan'
    REDEEM = 'redeem'

    OPERATION_TARGET_TYPE = (
        (LOAN, u'债权'),
        (REDEEM, u'赎回'),
    )


class OperationType(object):
    LOAN_ADD = 'LOAN_ADD'
    LOAN_AUDIT = 'LOAN_AUDIT'
    LOAN_REJECT = 'LOAN_REJECT'
    LOAN_EDIT = 'LOAN_EDIT'
    REDEEM_AUDIT_PASS = 'REDEEM_AUDIT_PASS'
    REDEEM_AUDIT_REJECT = 'REDEEM_AUDIT_REJECT'
    OPERATION_TYPE_MAP = (
        (LOAN_ADD, u'增加债权信息'),
        (LOAN_AUDIT, u'审核债权信息'),
        (LOAN_REJECT, u'驳回债权信息'),
        (LOAN_EDIT, u'编辑债权信息'),
        (REDEEM_AUDIT_PASS, u'审核通过赎回申请'),
        (REDEEM_AUDIT_REJECT, u'驳回赎回申请'),
    )

BILL_TYPE_DEPOSIT = 'DEPOSIT'
BILL_TYPE_WITHDRAW = 'WITHDRAW'
BILL_TYPE_INTEREST = 'INTEREST'
BILL_TYPE_PAYBACK = 'PAYBACK'
BILL_TYPE_CHOICE = (
    (BILL_TYPE_DEPOSIT, u'买入'),
    (BILL_TYPE_PAYBACK, u'超投返款'),
    (BILL_TYPE_WITHDRAW, u'赎回'),
    (BILL_TYPE_INTEREST, u'结息'),
)

REDEEM_WAITING = 'WAITING'
REDEEM_APPROVED = 'APPROVED'
REDEEM_REJECT = 'REJECT'
REDEEM_SUCCESS = 'SUCCESS'
REDEEM_FAIL = 'FAIL'
REDEEM_STATUS_CHOICE = (
    (REDEEM_WAITING, u'待审核'),
    (REDEEM_APPROVED, u'赎回中'),
    (REDEEM_REJECT, u'已驳回'),
    (REDEEM_SUCCESS, u'赎回成功'),
    (REDEEM_FAIL, u'赎回失败'),
)

# 单位为分
EVERY_DAY_OF_MAX_REDEEM_AMOUNT = 10000000
PERSONAL_MAX_DEPOSIT = 50000000

DAILY_QUOTA_STATUS_UNSET = 'UNSET'
DAILY_QUOTA_STATUS_APPROVING = 'APPROVING'
DAILY_QUOTA_STATUS_APPROVED = 'APPROVED'
DAILY_QUOTA_STATUS_REFUSED = 'REFUSED'
DAILY_QUOTA_STATUS_CANCELED = 'CANCELED'
DAILY_QUOTA_STATUS_CHOICES = (
    (DAILY_QUOTA_STATUS_UNSET, u'未设置'),
    (DAILY_QUOTA_STATUS_APPROVING, u'待审核'),
    (DAILY_QUOTA_STATUS_APPROVED, u'已审核'),
    (DAILY_QUOTA_STATUS_REFUSED, u'已拒绝'),
    (DAILY_QUOTA_STATUS_CANCELED, u'已取消')
)

LOAN_OUT_STATUS_RESERVE_TRANSFER_WAITING_PAY = 'RESERVE_TRANSFER_WAITING_PAY'
LOAN_OUT_STATUS_RESERVE_TRANSFER_SUCCESS = 'RESERVE_TRANSFER_SUCCESS'
LOAN_OUT_STATUS_RESERVE_TRANSFER_FAIL = 'RESERVE_TRANSFER_FAIL'
LOAN_OUT_STATUS_WAITING_PAY = 'WAITING_PAY'
LOAN_OUT_STATUS_SUCCESS = 'SUCCESS'
LOAN_OUT_STATUS_FAIL = 'FAIL'
LOAN_OUT_STATUS_CHOICES = (
    (LOAN_OUT_STATUS_RESERVE_TRANSFER_WAITING_PAY, u'放款准备金垫付利息支付中'),
    (LOAN_OUT_STATUS_RESERVE_TRANSFER_SUCCESS, u'放款准备金垫付利息支付成功'),
    (LOAN_OUT_STATUS_RESERVE_TRANSFER_FAIL, u'放款准备金垫付利息支付失败'),
    (LOAN_OUT_STATUS_WAITING_PAY, u'放款支付中'),
    (LOAN_OUT_STATUS_SUCCESS, u'放款成功'),
    (LOAN_OUT_STATUS_FAIL, u'放款失败')
)
