update user set experience_balance=experience_balance+3642200 where mobile = '13051419958';
update user set experience_balance=experience_balance+3090200 where mobile = '13264078502';
update user set experience_balance=experience_balance+13300 where mobile = '13315488052';
update user set experience_balance=experience_balance+2701100 where mobile = '13331266638';
update user set experience_balance=experience_balance+2000000 where mobile = '13522850086';
update user set experience_balance=experience_balance+2510000 where mobile = '13611099066';
update user set experience_balance=experience_balance+286500 where mobile = '13683662819';
update user set experience_balance=experience_balance+1500000 where mobile = '13731747847';
update user set experience_balance=experience_balance+80010000 where mobile = '13801360131';
update user set experience_balance=experience_balance+5000 where mobile = '13930270734';
update user set experience_balance=experience_balance+5000000 where mobile = '15110026455';
update user set experience_balance=experience_balance+15685100 where mobile = '15830389109';
update user set experience_balance=experience_balance+100000 where mobile = '18201449802';
update user set experience_balance=experience_balance+2582300 where mobile = '18516974797';
update user set experience_balance=experience_balance+255700 where mobile = '18647166286';
update user set experience_balance=experience_balance+111500 where mobile = '18801453273';
update user set experience_balance=experience_balance+829500 where mobile = '18931772989';

insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13051419958'), 'IN',3642200, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',36422,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13264078502'), 'IN',3090200, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',30902,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13315488052'), 'IN',13300, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',133,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13331266638'), 'IN',2701100, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',27011,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13522850086'), 'IN',2000000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',20000,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13611099066'), 'IN',2510000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',25100,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13683662819'), 'IN',286500, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',2865,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13731747847'), 'IN',1500000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',15000,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13801360131'), 'IN',80010000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',800100,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13930270734'), 'IN',5000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',50,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '15110026455'), 'IN',5000000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',50000,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '15830389109'), 'IN',15685100, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',156851,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18201449802'), 'IN',100000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',1000,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18516974797'), 'IN',2582300, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',25823,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18647166286'), 'IN',255700, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',2557,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18801453273'), 'IN',111500, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',1115,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18931772989'), 'IN',829500, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',8295,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;