BEGIN ;
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('中国工商银行', 'ICBC', '/images/bank/ICBC.jpg', 5000000, 5000000, 'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('中国建设银行', 'CCB', '/images/bank/CCB.jpg', 5000000, 5000000,'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('中国农业银行', 'ABC', '/images/bank/ABC.jpg', 5000000, 5000000,'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('招商银行', 'CMB', '/images/bank/CMB.jpg', 100000, 1000000, 'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('中国银行', 'BOC', '/images/bank/BOC.jpg', 5000000, 5000000,'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('中信银行', 'CITIC', '/images/bank/CITIC.jpg', 5000000, 5000000,'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('中国民生银行', 'CMBC', '/images/bank/CMBC.jpg', 5000000, 5000000,'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('中国光大银行', 'CEB', '/images/bank/CEB.jpg', 5000000, 5000000, 'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('交通银行', 'COMM', '/images/bank/COMM.jpg', 5000000, 5000000,'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('兴业银行', 'CIB', '/images/bank/CIB.jpg', 5000000, 5000000, 'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('平安银行', 'SPAB', '/images/bank/SPAB.jpg', 5000000, 5000000, 'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('浦东发展银行', 'SPDB', '/images/bank/SPDB.jpg', 5000000, 5000000, 'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('邮储银行', 'PSBC', '/images/bank/PSBC.jpg', 0, 0, 'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('广发银行', 'GDB', '/images/bank/GDB.jpg', 5000000, 5000000,'sidneygao', now());
insert into bank(name,bank_code,image_url,single_amount,single_day_amount,created_by,created_time) values('华夏银行', 'HXB', '/images/bank/HXB.jpg', 0, 0,'sidneygao', now());
COMMIT ;