BEGIN;
CREATE TABLE `activity`.`user_lottery_record` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mobile` VARCHAR(18) NOT NULL,
  `login_name` VARCHAR(25) NOT NULL,
  `prize` VARCHAR(50) NOT NULL,
  `lottery_time` DATETIME NOT NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT FK_USER_LOTTERY_NUMBER_MOBILE_REF_USER_MOBILE FOREIGN KEY (`mobile`) REFERENCES `aa`.`user` (`mobile`)
)
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;
COMMIT;