update user set experience_balance=experience_balance+36422 where mobile = '13051419958';
update user set experience_balance=experience_balance+30902 where mobile = '13264078502';
update user set experience_balance=experience_balance+133 where mobile = '13315488052';
update user set experience_balance=experience_balance+27011 where mobile = '13331266638';
update user set experience_balance=experience_balance+20000 where mobile = '13522850086';
update user set experience_balance=experience_balance+25100 where mobile = '13611099066';
update user set experience_balance=experience_balance+2865 where mobile = '13683662819';
update user set experience_balance=experience_balance+15000 where mobile = '13731747847';
update user set experience_balance=experience_balance+800100 where mobile = '13801360131';
update user set experience_balance=experience_balance+50 where mobile = '13930270734';
update user set experience_balance=experience_balance+50000 where mobile = '15110026455';
update user set experience_balance=experience_balance+156851 where mobile = '15830389109';
update user set experience_balance=experience_balance+1000 where mobile = '18201449802';
update user set experience_balance=experience_balance+25823 where mobile = '18516974797';
update user set experience_balance=experience_balance+2557 where mobile = '18647166286';
update user set experience_balance=experience_balance+1115 where mobile = '18801453273';
update user set experience_balance=experience_balance+8295 where mobile = '18931772989';

insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13051419958'), 'IN',36422, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',36422,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13264078502'), 'IN',30902, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',30902,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13315488052'), 'IN',133, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',133,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13331266638'), 'IN',27011, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',27011,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13522850086'), 'IN',20000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',20000,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13611099066'), 'IN',25100, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',25100,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13683662819'), 'IN',2865, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',2865,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13731747847'), 'IN',15000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',15000,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13801360131'), 'IN',800100, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',800100,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '13930270734'), 'IN',50, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',50,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '15110026455'), 'IN',50000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',50000,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '15830389109'), 'IN',156851, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',156851,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18201449802'), 'IN',1000, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',1000,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18516974797'), 'IN',25823, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',25823,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18647166286'), 'IN',2557, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',2557,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18801453273'), 'IN',1115, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',1115,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;
insert into experience_bill (`login_name`,`operation_type`,`amount`,`business_type`,`note`,`created_time`) select (select login_name from user where mobile = '18931772989'), 'IN',8295, 'DIVIDE_MONEY', CONCAT('恭喜您在瓜分体验金活动中获得体验金：',8295,'元体验金，获奖时间：',date_format(now(), '%c/%e/%y %l:%i %p')),now() from dual;