server:
  port: 30000
spring:
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://${common.jdbc.host}:${common.jdbc.port}/fudian?useUnicode=true&characterEncoding=UTF-8
    username: ${common.jdbc.username}
    password: ${common.jdbc.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      connection-timeout: 10000
  redis:
    host: ${common.redis.host}
    port: ${common.redis.port}
    database: 10
    jedis:
      pool:
        max-active: 50
        max-wait: 3s
        min-idle: 10
        max-idle: 15

bank:
  merchant: M02608959047521001
  merchantUserName: MU02608959047731001
  merchantAccountNo: MA02608959047771001
  pfx-password: 123456
  pfx-path: classpath:cfca/p2p.pfx
  cer-path: classpath:cfca/bank.cer
  crl-path: classpath:cfca/bank.crl
  bank-url: http://116.62.202.105:56502
#  web-callback-return-url: http://localhost:8080/callback/return-url
#  m-callback-return-url: http://localhost:8080/m/callback/return-url
#  mobile-callback-return-url: http://118.187.56.164:30000/callback/return-url
#  callback-notify-url: http://118.187.56.164:30000/callback/notify-url

  web-callback-return-url: http://localhost:8484/callback/return-url
  m-callback-return-url: http://localhost:8484/m/callback/return-url
  mobile-callback-return-url: http://118.187.56.164:30000/callback/return-url
  callback-notify-url: http://118.187.56.164:30001/callback/notify-url

mybatis:
  type-aliases-package: com.tuotiansudai.fudian.mapper

redisson:
  address: redis://${common.redis.host}:${common.redis.port}
  timeout: 10000
  connectionPoolSize: 50
  database: 10
