DROP TABLE IF EXISTS QRTZ_EXECUTION_LOGS;

CREATE TABLE QRTZ_EXECUTION_LOGS (
  ID             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  SCHED_NAME     VARCHAR(120)    NOT NULL,
  TRIGGER_NAME   VARCHAR(200)    NOT NULL,
  TRIGGER_GROUP  VARCHAR(200)    NOT NULL,
  JOB_NAME       VARCHAR(200)    NOT NULL,
  JOB_GROUP      VARCHAR(200)    NOT NULL,
  FIRE_TIME      BIGINT(13)      NOT NULL,
  DESCRIPTION    VARCHAR(250)    NULL,
  JOB_CLASS_NAME VARCHAR(250)    NOT NULL,
  EXECUTE_STATUS VARCHAR(16)     NOT NULL,
  JOB_DATA       TEXT            NULL,
  EXCEPTION      TEXT            NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB;
