signin:
  image: "leoshi/ttsd-signin-flask"
  environment:
    - "TZ=Asia/Shanghai"
  volumes:
    - .:/app
    - /var/log/signin:/var/log/signin
  ports:
    - "31000:80"
  command: ["/usr/bin/supervisord"]
