# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='debtor',
            field=models.CharField(max_length=60),
        ),
    ]
