# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDailyFundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('loan_remain_amount', models.PositiveIntegerField(default=0)),
                ('quota_amount', models.PositiveIntegerField(default=0)),
                ('config_quota_amount', models.PositiveIntegerField(null=True)),
                ('config_quota_status', models.CharField(choices=[(b'UNSET', '\u672a\u8bbe\u7f6e'), (b'APPROVING', '\u5f85\u5ba1\u6838'), (b'APPROVED', '\u5df2\u5ba1\u6838'), (b'REFUSED', '\u5df2\u62d2\u7edd'), (b'CANCELED', '\u5df2\u53d6\u6d88')], default=b'UNSET', max_length=20)),
                ('invest_amount', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'current_daily_fund_info',
            },
        ),
    ]
