# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('approver', models.CharField(max_length=25)),
                ('approved_time', models.DateTimeField(blank=True, null=True)),
                ('login_name', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[(b'WAITING', '\u5f85\u5ba1\u6838'), (b'APPROVED', '\u5df2\u5ba1\u6838'), (b'DENIED', '\u5df2\u9a73\u56de')], default=b'WAITING', max_length=20)),
                ('source', models.CharField(choices=[(b'WEB', '\u7f51\u7ad9'), (b'WE_CHAT', '\u5fae\u4fe1'), (b'IOS', 'iOS'), (b'ANDROID', 'Android')], default=b'WEB', max_length=10)),
            ],
            options={
                'db_table': 'current_withdraw',
            },
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='currentwithdraw',
            name='current_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='current_rest.CurrentAccount'),
        ),
    ]
