# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0002_currentdailyfundinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='current_rest.CurrentAccount')),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[(b'APPROVING', '\u5f85\u5ba1\u6838'), (b'APPROVED', '\u5df2\u5ba1\u6838'), (b'EXPIRED', '\u5df2\u8fc7\u671f'), (b'REJECT', '\u5df2\u9a73\u56de')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[(b'LOAN_ADD', '\u589e\u52a0\u503a\u6743\u4fe1\u606f'), (b'LOAN_AUDIT', '\u5ba1\u6838\u503a\u6743\u4fe1\u606f'), (b'LOAN_REJECT', '\u9a73\u56de\u503a\u6743\u4fe1\u606f'), (b'LOAN_EDIT', '\u7f16\u8f91\u503a\u6743\u4fe1\u606f')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='current_rest.Loan'),
        ),
    ]
