# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0002_currentdailyfundinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbill',
            name='bill_type',
            field=models.CharField(choices=[(b'DEPOSIT', '\u4e70\u5165'), (b'PAYBACK', '\u8d85\u6295\u8fd4\u6b3e'), (b'WITHDRAW', '\u8d4e\u56de'), (b'INTEREST', '\u7ed3\u606f')], max_length=10),
        ),
        migrations.AlterField(
            model_name='currentdeposit',
            name='status',
            field=models.CharField(choices=[(b'WAITING_PAY', '\u5f85\u652f\u4ed8'), (b'SUCCESS', '\u4e70\u5165\u6210\u529f'), (b'FAIL', '\u4e70\u5165\u5931\u8d25'), (b'OVER_PAY', '\u8d85\u6295'), (b'APPLYING_PAYBACK', '\u8d85\u6295\u8fd4\u6b3e\u7533\u8bf7\u4e2d'), (b'PAYBACK_SUCCESS', '\u8d85\u6295\u8fd4\u6b3e\u6210\u529f'), (b'PAYBACK_FAIL', '\u8d85\u6295\u8fd4\u6b3e\u5931\u8d25')], default=b'WAITING_PAY', max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[(b'APPROVING', '\u5f85\u5ba1\u6838'), (b'APPROVED', '\u5df2\u5ba1\u6838'), (b'EXPIRED', '\u5df2\u8fc7\u671f'), (b'REJECT', '\u5df2\u9a73\u56de')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[(b'LOAN_ADD', '\u589e\u52a0\u503a\u6743\u4fe1\u606f'), (b'LOAN_AUDIT', '\u5ba1\u6838\u503a\u6743\u4fe1\u606f'), (b'LOAN_REJECT', '\u9a73\u56de\u503a\u6743\u4fe1\u606f'), (b'LOAN_EDIT', '\u7f16\u8f91\u503a\u6743\u4fe1\u606f')], max_length=100, null=True),
        ),
    ]
