# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0002_currentdailyfundinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaccount',
            name='mobile',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[(b'APPROVING', '\u5f85\u5ba1\u6838'), (b'APPROVED', '\u5df2\u5ba1\u6838'), (b'EXPIRED', '\u5df2\u8fc7\u671f'), (b'REJECT', '\u5df2\u9a73\u56de')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[(b'LOAN_ADD', '\u589e\u52a0\u503a\u6743\u4fe1\u606f'), (b'LOAN_AUDIT', '\u5ba1\u6838\u503a\u6743\u4fe1\u606f'), (b'LOAN_REJECT', '\u9a73\u56de\u503a\u6743\u4fe1\u606f'), (b'LOAN_EDIT', '\u7f16\u8f91\u503a\u6743\u4fe1\u606f')], max_length=100, null=True),
        ),
    ]
