# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0003_auto_20170712_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_type', models.CharField(choices=[(b'loan', '\u503a\u6743')], max_length=50)),
                ('refer_pk', models.IntegerField()),
                ('operator', models.CharField(max_length=50)),
                ('operation_type', models.CharField(choices=[(b'LOAN_ADD', '\u589e\u52a0\u503a\u6743\u4fe1\u606f'), (b'LOAN_AUDIT', '\u5ba1\u6838\u503a\u6743\u4fe1\u606f')], max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'operation_log',
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='type',
            field=models.CharField(choices=[(b'HOUSE', '\u623f\u4ea7\u62b5\u62bc\u501f\u6b3e'), (b'VEHICLE', '\u8f66\u8f86\u62b5\u62bc\u501f\u6b3e'), (b'FACTORING', '\u4f01\u4e1a\u7ecf\u8425\u6027\u501f\u6b3e-\u4fdd\u7406'), (b'BILL', '\u4f01\u4e1a\u7ecf\u8425\u6027\u501f\u6b3e-\u7968\u636e'), (b'SHUIYI', '\u7a0e\u6613\u7ecf\u8425\u6027\u501f\u6b3e'), (b'HUIZU', '\u6c7d\u8f66\u878d\u8d44\u79df\u8d41')], max_length=40),
        ),
    ]
