# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0003_auto_20170801_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLoanOutHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('login_name', models.CharField(default=b'testName', max_length=25)),
                ('interest_amount', models.PositiveIntegerField(default=0)),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('bill_date', models.DateField()),
                ('status', models.CharField(choices=[(b'RESERVE_TRANSFER_WAITING_PAY', '\u653e\u6b3e\u51c6\u5907\u91d1\u57ab\u4ed8\u5229\u606f\u652f\u4ed8\u4e2d'), (b'RESERVE_TRANSFER_SUCCESS', '\u653e\u6b3e\u51c6\u5907\u91d1\u57ab\u4ed8\u5229\u606f\u652f\u4ed8\u6210\u529f'), (b'RESERVE_TRANSFER_FAIL', '\u653e\u6b3e\u51c6\u5907\u91d1\u57ab\u4ed8\u5229\u606f\u652f\u4ed8\u5931\u8d25'), (b'WAITING_PAY', '\u653e\u6b3e\u652f\u4ed8\u4e2d'), (b'SUCCESS', '\u653e\u6b3e\u6210\u529f'), (b'FAIL', '\u653e\u6b3e\u5931\u8d25')], default=b'RESERVE_TRANSFER_WAITING_PAY', max_length=100)),
            ],
            options={
                'db_table': 'current_loan_out_history',
            },
        ),
    ]
