# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0003_auto_20170728_1828'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fundallocation',
            table='fund_allocation',
        ),
    ]
