# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0004_currentloanouthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentloanouthistory',
            name='login_name',
        ),
        migrations.AddField(
            model_name='currentloanouthistory',
            name='agent_account',
            field=models.CharField(default=b'agent', max_length=25),
        ),
        migrations.AddField(
            model_name='currentloanouthistory',
            name='reserve_account',
            field=models.CharField(default=b'reserve', max_length=25),
        ),
    ]
