# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0004_auto_20170801_1929'),
        ('current_rest', '0003_auto_20170801_1454'),
    ]

    operations = [
    ]
