# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0005_loanrepay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'DONE', '\u5df2\u5904\u7406'), (b'PENDING', '\u672a\u5904\u7406')], max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=25)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('handler_role', models.CharField(max_length=50, null=False)),
                ('handler_name', models.CharField(max_length=25, null=True)),
                ('handler_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
