# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0005_auto_20170803_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='mobile',
            field=models.CharField(default=b'mobile', max_length=11, unique=True)
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='username',
            field=models.CharField(default=b'username', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentloanouthistory',
            name='agent_account',
            field=models.CharField(default=b'sidneygao', max_length=25),
        ),
        migrations.AlterField(
            model_name='currentloanouthistory',
            name='reserve_account',
            field=models.CharField(default=b'sidneygao', max_length=25),
        ),
    ]
