# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0006_auto_20170803_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='current_rest.CurrentAccount')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='current_rest.Loan')),
            ],
            options={
                'db_table': 'fund_allocation',
            },
        ),
        migrations.CreateModel(
            name='LoanRepay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('approver', models.CharField(max_length=25, null=True)),
                ('approved_time', models.DateTimeField(blank=True, null=True)),
                ('repay_amount', models.PositiveIntegerField()),
                ('submit_name', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[(b'WAITING', '\u5f85\u5ba1\u6838'), (b'APPROVED', '\u5df2\u5ba1\u6838'), (b'DENIED', '\u5df2\u9a73\u56de')], max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='current_rest.Loan')),
            ],
            options={
                'db_table': 'loan_repay',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'DONE', '\u5df2\u5904\u7406'), (b'PENDING', '\u672a\u5904\u7406')], max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=25)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('handler_role', models.CharField(max_length=50)),
                ('handler_name', models.CharField(max_length=25, null=True)),
                ('handler_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.AlterField(
            model_name='currentredeem',
            name='status',
            field=models.CharField(choices=[(b'WAITING', '\u5f85\u5ba1\u6838'), (b'APPROVED', '\u8d4e\u56de\u4e2d'), (b'REJECT', '\u5df2\u9a73\u56de'), (b'SUCCESS', '\u8d4e\u56de\u6210\u529f'), (b'FAIL', '\u8d4e\u56de\u5931\u8d25')], default=b'WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[(b'LOAN_ADD', '\u589e\u52a0\u503a\u6743\u4fe1\u606f'), (b'LOAN_AUDIT', '\u5ba1\u6838\u503a\u6743\u4fe1\u606f'), (b'LOAN_REJECT', '\u9a73\u56de\u503a\u6743\u4fe1\u606f'), (b'LOAN_EDIT', '\u7f16\u8f91\u503a\u6743\u4fe1\u606f'), (b'LOAN_REPAY_PASS', '\u5ba1\u6838\u901a\u8fc7\u8fd8\u6b3e\u7533\u8bf7'), (b'LOAN_REPAY_REJECT', '\u9a73\u56de\u8fd8\u6b3e\u7533\u8bf7'), (b'REDEEM_AUDIT_PASS', '\u5ba1\u6838\u901a\u8fc7\u8d4e\u56de\u7533\u8bf7'), (b'REDEEM_AUDIT_REJECT', '\u9a73\u56de\u8d4e\u56de\u7533\u8bf7')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='refer_type',
            field=models.CharField(choices=[(b'loan', '\u503a\u6743'), (b'redeem', '\u8d4e\u56de'), (b'loan_repay', '\u8fd8\u6b3e')], max_length=50),
        ),
    ]
