# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0006_auto_20170803_1120'),
        ('current_rest', '0005_auto_20170803_1634'),
    ]

    operations = [
    ]
