# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0007_merge_20170808_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentloanouthistory',
            name='agent_account',
            field=models.CharField(default=b'sidneygao', max_length=25),
        ),
        migrations.AlterField(
            model_name='currentloanouthistory',
            name='reserve_account',
            field=models.CharField(default=b'sidneygao', max_length=25),
        ),
        migrations.AlterField(
            model_name='currentredeem',
            name='status',
            field=models.CharField(choices=[(b'WAITING', '\u5f85\u5ba1\u6838'), (b'APPROVED', '\u8d4e\u56de\u4e2d'), (b'REJECT', '\u5df2\u9a73\u56de'), (b'SUCCESS', '\u8d4e\u56de\u6210\u529f'), (b'FAIL', '\u8d4e\u56de\u5931\u8d25')], default=b'WAITING', max_length=20),
        ),
    ]
