# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0006_auto_20170807_1430'),
        ('current_rest', '0008_auto_20170808_1054'),
    ]

    operations = [
    ]
