# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_rest', '0009_merge_20170808_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaccount',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='mobile',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
