# coding=utf-8
LOAN_STATUS_APPROVING = 'APPROVING'
LOAN_STATUS_APPROVED = 'APPROVED'
LOAN_STATUS_EXPIRED = 'EXPIRED'
LOAN_STATUS_REJECT = 'REJECT'

LOAN_TYPE_HOUSE = 'HOUSE'
LOAN_TYPE_VEHICLE = 'VEHICLE'
LOAN_TYPE_FACTORING = 'FACTORING'
LOAN_TYPE_BILL = 'BILL'
LOAN_TYPE_HUIZU = 'HUIZU'
LOAN_TYPE_SHUIYI = 'SHUIYI'

LOAN_TYPE_CHOICES = (
    (LOAN_TYPE_HOUSE, u'房产抵押借款'),
    (LOAN_TYPE_VEHICLE, u'车辆抵押借款'),
    (LOAN_TYPE_FACTORING, u'企业经营性借款-保理'),
    (LOAN_TYPE_BILL, u'企业经营性借款-票据'),
    (LOAN_TYPE_SHUIYI, u'税易经营性借款'),
    (LOAN_TYPE_HUIZU, u'汽车融资租赁')
)
LOAN_STATUS_CHOICES = (
    (LOAN_STATUS_APPROVING, u'待审核'),
    (LOAN_STATUS_APPROVED, u'已审核'),
    (LOAN_STATUS_EXPIRED, u'已过期'),
    (LOAN_STATUS_REJECT, u'已驳回'),

)

REDEEM_WAITING = 'WAITING'
REDEEM_DOING = 'DOING'
REDEEM_REJECT = 'REJECT'
REDEEM_SUCCESS = 'SUCCESS'
REDEEM_FAIL = 'FAIL'
REDEEM_STATUS_CHOICE = (
    (REDEEM_WAITING, u'待审核'),
    (REDEEM_DOING, u'赎回中'),
    (REDEEM_REJECT, u'已驳回'),
    (REDEEM_SUCCESS, u'赎回成功'),
    (REDEEM_FAIL, u'赎回失败'),
)
