# coding=utf-8
LOAN_STATUS_APPROVING = 'APPROVING'
LOAN_STATUS_APPROVED = 'APPROVED'
LOAN_STATUS_EXPIRED = 'EXPIRED'
LOAN_STATUS_REJECT = 'REJECT'

LOAN_TYPE_HOUSE = 'HOUSE'
LOAN_TYPE_VEHICLE = 'VEHICLE'
LOAN_TYPE_FACTORING = 'FACTORING'
LOAN_TYPE_BILL = 'BILL'
LOAN_TYPE_HUIZU = 'HUIZU'
LOAN_TYPE_SHUIYI = 'SHUIYI'

LOAN_TYPE_CHOICES = (
    (LOAN_TYPE_HOUSE, u'房产抵押借款'),
    (LOAN_TYPE_VEHICLE, u'车辆抵押借款'),
    (LOAN_TYPE_FACTORING, u'企业经营性借款-保理'),
    (LOAN_TYPE_BILL, u'企业经营性借款-票据'),
    (LOAN_TYPE_SHUIYI, u'税易经营性借款'),
    (LOAN_TYPE_HUIZU, u'汽车融资租赁')
)
LOAN_STATUS_CHOICES = (
    (LOAN_STATUS_APPROVING, u'待审核'),
    (LOAN_STATUS_APPROVED, u'已审核'),
    (LOAN_STATUS_EXPIRED, u'已过期'),
    (LOAN_STATUS_REJECT, u'已驳回'),

)
