# -*- coding: utf-8 -*-
"""
Django settings for current project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't@7h4!s_wi!zf*86!$)%xtu$_#7(rmd-)4d&(u20vdmjvu&_(('

# ENVIRONMENT
PRODUCT = False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not PRODUCT

ALLOWED_HOSTS = ["*"]

ROOT_URLCONF = 'current_console.urls'

WSGI_APPLICATION = 'wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# ===signIn module start===
SIGN_IN_HOST = 'http://127.0.0.1'
SIGN_IN_PORT = '5000'
LOGIN_URL = 'http://localhost:9080/login'
# ===signIn module end===

# rest service url
REST_SERVICE_HOST = '127.0.0.1'
REST_SERVICE_PORT = '8000'
REST_PATH = ''
REST_TIME_OUT = 300

LOGGING_DIR = '/var/log/current_console'

# reload setting for local
setting_local_file = '/workspace/deploy-config/ttsd-current/console_settings.py'
if not os.path.isfile(setting_local_file):
    setting_local_file = os.path.join(BASE_DIR, "settings_local.py")

if os.path.isfile(setting_local_file):
    exec (compile(open(setting_local_file).read(), setting_local_file, 'exec'))

# Application definition

INSTALLED_APPS = [
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'current_console']

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'current_console.middleware.TTSDSessionManager',
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'TEST': {
            'CHARSET': 'UTF8',
        },

    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'current_console.context_processors.login_user_name',
            ],
        },
    },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(name)s] [%(module)s:%(funcName)s:%(lineno)d] [%(levelname)s]- %(message)s'
        }
    },
    'filters': {
    },
    'handlers': {
        'default': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGGING_DIR + '/current_console.log',
            'when': 'midnight',
            'backupCount': 5,
            'formatter': 'standard',
        },
        'request_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGGING_DIR + '/request.log',
            'when': 'midnight',
            'backupCount': 5,
            'formatter': 'standard',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': False
        },
        'current_console': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': False
        },
        'django.request': {
            'handlers': ['default', 'request_handler'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}
