BEGIN ;
ALTER TABLE recharge ADD COLUMN source VARCHAR(10) ;
ALTER TABLE user ADD COLUMN source VARCHAR(10) ;
ALTER TABLE invest ADD COLUMN source VARCHAR(10) ;
ALTER TABLE withdraw_cash ADD COLUMN source VARCHAR(10) ;
COMMIT ;