CREATE TABLE `special_invest_lucky_draw` (
`id` VARCHAR(32) NOT NULL,
`invest_id` VARCHAR(32) NOT NULL,
`user_id` VARCHAR(32) NOT NULL,
`type` VARCHAR(16) NOT NULL,
`created_time` DATE NOT NULL,
`prize_level` VARCHAR(8) NOT NULL,
`amount` DOUBLE NULL,
`award_time` DATE NULL,
`is_valid` boolean,

PRIMARY KEY (`id`),
CONSTRAINT FK_SPECIAL_INVEST_LUCKY_DRAW_USER_ID_REF_USER_ID FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
CONSTRAINT FK_SPECIAL_INVEST_LUCKY_DRAW_INVEST_ID_REF_INVEST_ID FOREIGN KEY (`invest_id`) REFERENCES `invest` (`id`),
KEY SPECIAL_INVEST_LUCKY_DRAW_TYPE (`type`)
)
ENGINE=INNODB
DEFAULT CHARSET=utf8;
